// default package
// Generated 30-Mar-2018 12:11:34 by Hibernate Tools 5.1.0.Alpha1
package com.avee.domain;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PpaBranchCodeDetails generated by hbm2java
 */

@Entity
@Table(name = "PPA_branch_code_details", catalog = "Pharma")
public class PpaBranchCodeDetails implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private int id;
	private String branchCode;
	private String branchName;
	private String branchDesc;

	public PpaBranchCodeDetails() {
	}

	public PpaBranchCodeDetails(int id) {
		this.id = id;
	}

	public PpaBranchCodeDetails(int id, String branchCode, String branchName, String branchDesc) {
		this.id = id;
		this.branchCode = branchCode;
		this.branchName = branchName;
		this.branchDesc = branchDesc;
	}
	@Id
	@Column(name = "id", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "branch_code", length = 30)
	public String getBranchCode() {
		return this.branchCode;
	}

	public void setBranchCode(String branchCode) {
		this.branchCode = branchCode;
	}

	@Column(name = "branch_name", length = 100)
	public String getBranchName() {
		return this.branchName;
	}

	public void setBranchName(String branchName) {
		this.branchName = branchName;
	}

	@Column(name = "branch_desc", length = 100)
	public String getBranchDesc() {
		return this.branchDesc;
	}

	public void setBranchDesc(String branchDesc) {
		this.branchDesc = branchDesc;
	}

}
