// default package
// Generated 30-Mar-2018 12:11:34 by Hibernate Tools 5.1.0.Alpha1
package com.avee.domain;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PpaMaster500 generated by hbm2java
 */

@Entity
@Table(name = "PPA_MASTER_500", catalog = "Pharma")
public class PpaMaster500 implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private int id;
	private Date paymentDate;
	private String sbOcsCode;
	private String mbTradename;
	private String sbConLaLine;
	private Short localPayLineId;
	private String localPayLineDesc;
	private Double localPayLineValue;

	public PpaMaster500() {
	}

	public PpaMaster500(int id, Date paymentDate) {
		this.id = id;
		this.paymentDate = paymentDate;
	}

	public PpaMaster500(int id, Date paymentDate, String sbOcsCode, String mbTradename, String sbConLaLine,
			Short localPayLineId, String localPayLineDesc, Double localPayLineValue) {
		this.id = id;
		this.paymentDate = paymentDate;
		this.sbOcsCode = sbOcsCode;
		this.mbTradename = mbTradename;
		this.sbConLaLine = sbConLaLine;
		this.localPayLineId = localPayLineId;
		this.localPayLineDesc = localPayLineDesc;
		this.localPayLineValue = localPayLineValue;
	}
	@Id
	@Column(name = "id", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "payment_date", nullable = false, length = 27)
	public Date getPaymentDate() {
		return this.paymentDate;
	}

	public void setPaymentDate(Date paymentDate) {
		this.paymentDate = paymentDate;
	}

	@Column(name = "sb_ocs_code", length = 30)
	public String getSbOcsCode() {
		return this.sbOcsCode;
	}

	public void setSbOcsCode(String sbOcsCode) {
		this.sbOcsCode = sbOcsCode;
	}

	@Column(name = "mb_tradename", length = 30)
	public String getMbTradename() {
		return this.mbTradename;
	}

	public void setMbTradename(String mbTradename) {
		this.mbTradename = mbTradename;
	}

	@Column(name = "sb_con_la_line", length = 30)
	public String getSbConLaLine() {
		return this.sbConLaLine;
	}

	public void setSbConLaLine(String sbConLaLine) {
		this.sbConLaLine = sbConLaLine;
	}

	@Column(name = "local_pay_line_id")
	public Short getLocalPayLineId() {
		return this.localPayLineId;
	}

	public void setLocalPayLineId(Short localPayLineId) {
		this.localPayLineId = localPayLineId;
	}

	@Column(name = "local_pay_line_desc", length = 300)
	public String getLocalPayLineDesc() {
		return this.localPayLineDesc;
	}

	public void setLocalPayLineDesc(String localPayLineDesc) {
		this.localPayLineDesc = localPayLineDesc;
	}

	@Column(name = "local_pay_line_value", precision = 53, scale = 0)
	public Double getLocalPayLineValue() {
		return this.localPayLineValue;
	}

	public void setLocalPayLineValue(Double localPayLineValue) {
		this.localPayLineValue = localPayLineValue;
	}

}
