// default package
// Generated 30-Mar-2018 14:11:20 by Hibernate Tools 5.1.0.Alpha1
package com.avee.domain;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PpaMaster generated by hbm2java
 */
@Entity
@Table(name = "PPA_MASTER", catalog = "Pharma")
public class PpaMaster implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private int id;
	private Date paymentDate;
	private double contRate;
	private double stProfFee;
	private double spProfFee;
	private short expItemsLowerLimit;
	private short expItemsUpperLimit;
	private String mbOcsCode;
	private String mbCorName;
	private short mbShopNo;
	private String mbTradename;
	private String mbCorAddress1;
	private String mbCorAddress2;
	private String mbCorAddress3;
	private String mbCorAddress4;
	private String mbCorPostcode;
	private String mbName;
	private String mbPremAdd1;
	private String mbPremAdd2;
	private String mbPremAdd3;
	private String mbPremAdd4;
	private String mbPremPcode;
	private String mbFhsaCode;
	private String mbPpaAccCode;
	private String mbNameOfAccount;
	private String mbBankAccountNumber;
	private String mbBuildingSocRef;
	private String mbSortCode;
	private String mbTypeOfAccount;
	private String mbPaymentMethod;
	private double mbPayment;
	private String mbRemitDispDate;
	private String sb300;
	private String sbMbOcsCode;
	private String sbHaQcode;
	private String sbOcsCode;
	private String sbTaName;
	private String sbName;
	private String sbAddress1;
	private String sbAddress2;
	private String sbAddress3;
	private String sbAddressPostCode;
	private String sbHealthAuthority;
	private String sbConPpaCode;
	private String sbConLaLine;
	private double sbPayment;
	private short sbConFormsRec;
	private short sbConItemsSdr;
	private short sbConItemsZd;
	private short sbConFormsRb;
	private short sbConItemsRb;
	private double sbConDisc;
	private short sbConNumConAll;
	private String sbConAdjText;
	private short sbNoStproFees;
	private short sbNoSprofFees;
	private double sbNoEprescFees;
	private double sbRecovery;
	private short sbNoPrescNew;
	private double sbPrescRateNew;
	private double sbNoPrescOld;
	private double sbPrescRateOld;
	private double sbAdvPayment;
	private String sbAdvMonth;
	private short sbAdvItems;
	private short sbAdvChrg;
	private String sbOtherAdvReason;
	private String sbRecOfAdvReason;
	private double sbTotAuthByPpa;
	private double sbTotAuthByHa;
	private String sbDispDateMonth;
	private short sbDispDateYear;
	private double sbTotBasPrice;
	private double sbDiscount;
	private double sbTotBasPriceZd;
	private double sbOopExp;
	private double sbContAll;
	private double sbContCon;
	private double sbOxyCylMsk;
	private double sbOxyExp;
	private double sbOxyAdj;
	private double sbAdjVal;
	private double sbStProfFees;
	private double sbSpProfFees;
	private double sbMpPfees;
	private double sbPfees2a;
	private double sbPfees2b;
	private double sbPfees2c;
	private double sbPfees2d;
	private double sbPfees2e;
	private double sbPfees2f;
	private double sbPfees2g;
	private double sbExpPrescFees;
	private double sbAddProfPay;
	private double sbPrescChNew;
	private double sbPrescChOld;
	private double sbOtherAdj;
	private double sbSubBpTotCalc;
	private double sbReimbTotCalc;
	private double sbAddProfFees;
	private double sbRemunTot;
	private double sbTotDed;
	private double sbTotOfAcc;
	private double sbNetAmt;
	private double sbRecOfAdvCalc;
	private double sbOthAdjAdv;
	private double sbTotLaPay;
	private double sbTotLaOther;
	private double murNum;
	private double fp57NumForms;
	private double dispItemsNum;
	private double practicePayment;
	private double estabFee;
	private double murFee;
	private double nmsFee;
	private double repeatSetup;
	private double subTotalOfPrescFee;
	private double balDueRespOf;
	private double sbElhoseValue;
	private double sbAvgItemValue;
	private short localPayLineId;
	private String localPayLineDesc;
	private double localPayLineValue;
	private short wgAeLineType;
	private String wgAeIdentifier;
	private String wgAeReasonCode;
	private String wgAeDescription;
	private short wgAeNumPxs;
	private short expItemsLimit2;
	private double expValueLimit2;
	private short expItemsLimit1;
	private double expValueLimit1;
	private short expTotItems;
	private double expTotValue;
	private String expensiveItemLine;
	private String expItemDescription;
	private double expItemPack;
	private short expItemQty;
	private double expItemValue;
	private short expensiveItemForm;
	private short trlrBranchCount;
	private double trlrTotalValue;
	private double sbPfees2bHome;
	private double aurHomeFee;
	private double aurPremFee;
	private double stomaCustValue;
	private double recAddAdvPay;
	private double addAdvPay;
	private short sbEtpForms;
	private double sbEtpItems;
	private double nmsNum;
	private short nmsItem;
	private String createdBy;
	private Date createdDate;
	private String updatedBy;
	private Date updatedDate;

	public PpaMaster() {
	}

	public PpaMaster(int id, Date paymentDate, double contRate, double stProfFee, double spProfFee,
			short expItemsLowerLimit, short expItemsUpperLimit, short mbShopNo, double mbPayment, double sbPayment,
			short sbConFormsRec, short sbConItemsSdr, short sbConItemsZd, short sbConFormsRb, short sbConItemsRb,
			double sbConDisc, short sbConNumConAll, short sbNoStproFees, short sbNoSprofFees, double sbNoEprescFees,
			double sbRecovery, short sbNoPrescNew, double sbPrescRateNew, double sbNoPrescOld, double sbPrescRateOld,
			double sbAdvPayment, short sbAdvItems, short sbAdvChrg, double sbTotAuthByPpa, double sbTotAuthByHa,
			short sbDispDateYear, double sbTotBasPrice, double sbDiscount, double sbTotBasPriceZd, double sbOopExp,
			double sbContAll, double sbContCon, double sbOxyCylMsk, double sbOxyExp, double sbOxyAdj, double sbAdjVal,
			double sbStProfFees, double sbSpProfFees, double sbMpPfees, double sbPfees2a, double sbPfees2b,
			double sbPfees2c, double sbPfees2d, double sbPfees2e, double sbPfees2f, double sbPfees2g,
			double sbExpPrescFees, double sbAddProfPay, double sbPrescChNew, double sbPrescChOld, double sbOtherAdj,
			double sbSubBpTotCalc, double sbReimbTotCalc, double sbAddProfFees, double sbRemunTot, double sbTotDed,
			double sbTotOfAcc, double sbNetAmt, double sbRecOfAdvCalc, double sbOthAdjAdv, double sbTotLaPay,
			double sbTotLaOther, double murNum, double fp57NumForms, double dispItemsNum, double practicePayment,
			double estabFee, double murFee, double nmsFee, double repeatSetup, double subTotalOfPrescFee,
			double balDueRespOf, double sbElhoseValue, double sbAvgItemValue, short localPayLineId,
			double localPayLineValue, double expValueLimit2, double expValueLimit1, double expTotValue,
			double expItemPack, double expItemValue, double trlrTotalValue, double sbPfees2bHome, double aurHomeFee,
			double aurPremFee, double stomaCustValue, double recAddAdvPay, double addAdvPay, double sbEtpItems,
			double nmsNum, String createdBy, Date createdDate, Date updatedDate) {
		this.id = id;
		this.paymentDate = paymentDate;
		this.contRate = contRate;
		this.stProfFee = stProfFee;
		this.spProfFee = spProfFee;
		this.expItemsLowerLimit = expItemsLowerLimit;
		this.expItemsUpperLimit = expItemsUpperLimit;
		this.mbShopNo = mbShopNo;
		this.mbPayment = mbPayment;
		this.sbPayment = sbPayment;
		this.sbConFormsRec = sbConFormsRec;
		this.sbConItemsSdr = sbConItemsSdr;
		this.sbConItemsZd = sbConItemsZd;
		this.sbConFormsRb = sbConFormsRb;
		this.sbConItemsRb = sbConItemsRb;
		this.sbConDisc = sbConDisc;
		this.sbConNumConAll = sbConNumConAll;
		this.sbNoStproFees = sbNoStproFees;
		this.sbNoSprofFees = sbNoSprofFees;
		this.sbNoEprescFees = sbNoEprescFees;
		this.sbRecovery = sbRecovery;
		this.sbNoPrescNew = sbNoPrescNew;
		this.sbPrescRateNew = sbPrescRateNew;
		this.sbNoPrescOld = sbNoPrescOld;
		this.sbPrescRateOld = sbPrescRateOld;
		this.sbAdvPayment = sbAdvPayment;
		this.sbAdvItems = sbAdvItems;
		this.sbAdvChrg = sbAdvChrg;
		this.sbTotAuthByPpa = sbTotAuthByPpa;
		this.sbTotAuthByHa = sbTotAuthByHa;
		this.sbDispDateYear = sbDispDateYear;
		this.sbTotBasPrice = sbTotBasPrice;
		this.sbDiscount = sbDiscount;
		this.sbTotBasPriceZd = sbTotBasPriceZd;
		this.sbOopExp = sbOopExp;
		this.sbContAll = sbContAll;
		this.sbContCon = sbContCon;
		this.sbOxyCylMsk = sbOxyCylMsk;
		this.sbOxyExp = sbOxyExp;
		this.sbOxyAdj = sbOxyAdj;
		this.sbAdjVal = sbAdjVal;
		this.sbStProfFees = sbStProfFees;
		this.sbSpProfFees = sbSpProfFees;
		this.sbMpPfees = sbMpPfees;
		this.sbPfees2a = sbPfees2a;
		this.sbPfees2b = sbPfees2b;
		this.sbPfees2c = sbPfees2c;
		this.sbPfees2d = sbPfees2d;
		this.sbPfees2e = sbPfees2e;
		this.sbPfees2f = sbPfees2f;
		this.sbPfees2g = sbPfees2g;
		this.sbExpPrescFees = sbExpPrescFees;
		this.sbAddProfPay = sbAddProfPay;
		this.sbPrescChNew = sbPrescChNew;
		this.sbPrescChOld = sbPrescChOld;
		this.sbOtherAdj = sbOtherAdj;
		this.sbSubBpTotCalc = sbSubBpTotCalc;
		this.sbReimbTotCalc = sbReimbTotCalc;
		this.sbAddProfFees = sbAddProfFees;
		this.sbRemunTot = sbRemunTot;
		this.sbTotDed = sbTotDed;
		this.sbTotOfAcc = sbTotOfAcc;
		this.sbNetAmt = sbNetAmt;
		this.sbRecOfAdvCalc = sbRecOfAdvCalc;
		this.sbOthAdjAdv = sbOthAdjAdv;
		this.sbTotLaPay = sbTotLaPay;
		this.sbTotLaOther = sbTotLaOther;
		this.murNum = murNum;
		this.fp57NumForms = fp57NumForms;
		this.dispItemsNum = dispItemsNum;
		this.practicePayment = practicePayment;
		this.estabFee = estabFee;
		this.murFee = murFee;
		this.nmsFee = nmsFee;
		this.repeatSetup = repeatSetup;
		this.subTotalOfPrescFee = subTotalOfPrescFee;
		this.balDueRespOf = balDueRespOf;
		this.sbElhoseValue = sbElhoseValue;
		this.sbAvgItemValue = sbAvgItemValue;
		this.localPayLineId = localPayLineId;
		this.localPayLineValue = localPayLineValue;
		this.expValueLimit2 = expValueLimit2;
		this.expValueLimit1 = expValueLimit1;
		this.expTotValue = expTotValue;
		this.expItemPack = expItemPack;
		this.expItemValue = expItemValue;
		this.trlrTotalValue = trlrTotalValue;
		this.sbPfees2bHome = sbPfees2bHome;
		this.aurHomeFee = aurHomeFee;
		this.aurPremFee = aurPremFee;
		this.stomaCustValue = stomaCustValue;
		this.recAddAdvPay = recAddAdvPay;
		this.addAdvPay = addAdvPay;
		this.sbEtpItems = sbEtpItems;
		this.nmsNum = nmsNum;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
	}

	public PpaMaster(int id, Date paymentDate, double contRate, double stProfFee, double spProfFee,
			short expItemsLowerLimit, short expItemsUpperLimit, String mbOcsCode, String mbCorName, short mbShopNo,
			String mbTradename, String mbCorAddress1, String mbCorAddress2, String mbCorAddress3, String mbCorAddress4,
			String mbCorPostcode, String mbName, String mbPremAdd1, String mbPremAdd2, String mbPremAdd3,
			String mbPremAdd4, String mbPremPcode, String mbFhsaCode, String mbPpaAccCode, String mbNameOfAccount,
			String mbBankAccountNumber, String mbBuildingSocRef, String mbSortCode, String mbTypeOfAccount,
			String mbPaymentMethod, double mbPayment, String mbRemitDispDate, String sb300, String sbMbOcsCode,
			String sbHaQcode, String sbOcsCode, String sbTaName, String sbName, String sbAddress1, String sbAddress2,
			String sbAddress3, String sbAddressPostCode, String sbHealthAuthority, String sbConPpaCode,
			String sbConLaLine, double sbPayment, short sbConFormsRec, short sbConItemsSdr, short sbConItemsZd,
			short sbConFormsRb, short sbConItemsRb, double sbConDisc, short sbConNumConAll, String sbConAdjText,
			short sbNoStproFees, short sbNoSprofFees, double sbNoEprescFees, double sbRecovery, short sbNoPrescNew,
			double sbPrescRateNew, double sbNoPrescOld, double sbPrescRateOld, double sbAdvPayment, String sbAdvMonth,
			short sbAdvItems, short sbAdvChrg, String sbOtherAdvReason, String sbRecOfAdvReason, double sbTotAuthByPpa,
			double sbTotAuthByHa, String sbDispDateMonth, short sbDispDateYear, double sbTotBasPrice, double sbDiscount,
			double sbTotBasPriceZd, double sbOopExp, double sbContAll, double sbContCon, double sbOxyCylMsk,
			double sbOxyExp, double sbOxyAdj, double sbAdjVal, double sbStProfFees, double sbSpProfFees,
			double sbMpPfees, double sbPfees2a, double sbPfees2b, double sbPfees2c, double sbPfees2d, double sbPfees2e,
			double sbPfees2f, double sbPfees2g, double sbExpPrescFees, double sbAddProfPay, double sbPrescChNew,
			double sbPrescChOld, double sbOtherAdj, double sbSubBpTotCalc, double sbReimbTotCalc, double sbAddProfFees,
			double sbRemunTot, double sbTotDed, double sbTotOfAcc, double sbNetAmt, double sbRecOfAdvCalc,
			double sbOthAdjAdv, double sbTotLaPay, double sbTotLaOther, double murNum, double fp57NumForms,
			double dispItemsNum, double practicePayment, double estabFee, double murFee, double nmsFee,
			double repeatSetup, double subTotalOfPrescFee, double balDueRespOf, double sbElhoseValue,
			double sbAvgItemValue, short localPayLineId, String localPayLineDesc, double localPayLineValue,
			short wgAeLineType, String wgAeIdentifier, String wgAeReasonCode, String wgAeDescription, short wgAeNumPxs,
			short expItemsLimit2, double expValueLimit2, short expItemsLimit1, double expValueLimit1, short expTotItems,
			double expTotValue, String expensiveItemLine, String expItemDescription, double expItemPack,
			short expItemQty, double expItemValue, short expensiveItemForm, short trlrBranchCount,
			double trlrTotalValue, double sbPfees2bHome, double aurHomeFee, double aurPremFee, double stomaCustValue,
			double recAddAdvPay, double addAdvPay, short sbEtpForms, double sbEtpItems, double nmsNum, short nmsItem,
			String createdBy, Date createdDate, String updatedBy, Date updatedDate) {
		this.id = id;
		this.paymentDate = paymentDate;
		this.contRate = contRate;
		this.stProfFee = stProfFee;
		this.spProfFee = spProfFee;
		this.expItemsLowerLimit = expItemsLowerLimit;
		this.expItemsUpperLimit = expItemsUpperLimit;
		this.mbOcsCode = mbOcsCode;
		this.mbCorName = mbCorName;
		this.mbShopNo = mbShopNo;
		this.mbTradename = mbTradename;
		this.mbCorAddress1 = mbCorAddress1;
		this.mbCorAddress2 = mbCorAddress2;
		this.mbCorAddress3 = mbCorAddress3;
		this.mbCorAddress4 = mbCorAddress4;
		this.mbCorPostcode = mbCorPostcode;
		this.mbName = mbName;
		this.mbPremAdd1 = mbPremAdd1;
		this.mbPremAdd2 = mbPremAdd2;
		this.mbPremAdd3 = mbPremAdd3;
		this.mbPremAdd4 = mbPremAdd4;
		this.mbPremPcode = mbPremPcode;
		this.mbFhsaCode = mbFhsaCode;
		this.mbPpaAccCode = mbPpaAccCode;
		this.mbNameOfAccount = mbNameOfAccount;
		this.mbBankAccountNumber = mbBankAccountNumber;
		this.mbBuildingSocRef = mbBuildingSocRef;
		this.mbSortCode = mbSortCode;
		this.mbTypeOfAccount = mbTypeOfAccount;
		this.mbPaymentMethod = mbPaymentMethod;
		this.mbPayment = mbPayment;
		this.mbRemitDispDate = mbRemitDispDate;
		this.sb300 = sb300;
		this.sbMbOcsCode = sbMbOcsCode;
		this.sbHaQcode = sbHaQcode;
		this.sbOcsCode = sbOcsCode;
		this.sbTaName = sbTaName;
		this.sbName = sbName;
		this.sbAddress1 = sbAddress1;
		this.sbAddress2 = sbAddress2;
		this.sbAddress3 = sbAddress3;
		this.sbAddressPostCode = sbAddressPostCode;
		this.sbHealthAuthority = sbHealthAuthority;
		this.sbConPpaCode = sbConPpaCode;
		this.sbConLaLine = sbConLaLine;
		this.sbPayment = sbPayment;
		this.sbConFormsRec = sbConFormsRec;
		this.sbConItemsSdr = sbConItemsSdr;
		this.sbConItemsZd = sbConItemsZd;
		this.sbConFormsRb = sbConFormsRb;
		this.sbConItemsRb = sbConItemsRb;
		this.sbConDisc = sbConDisc;
		this.sbConNumConAll = sbConNumConAll;
		this.sbConAdjText = sbConAdjText;
		this.sbNoStproFees = sbNoStproFees;
		this.sbNoSprofFees = sbNoSprofFees;
		this.sbNoEprescFees = sbNoEprescFees;
		this.sbRecovery = sbRecovery;
		this.sbNoPrescNew = sbNoPrescNew;
		this.sbPrescRateNew = sbPrescRateNew;
		this.sbNoPrescOld = sbNoPrescOld;
		this.sbPrescRateOld = sbPrescRateOld;
		this.sbAdvPayment = sbAdvPayment;
		this.sbAdvMonth = sbAdvMonth;
		this.sbAdvItems = sbAdvItems;
		this.sbAdvChrg = sbAdvChrg;
		this.sbOtherAdvReason = sbOtherAdvReason;
		this.sbRecOfAdvReason = sbRecOfAdvReason;
		this.sbTotAuthByPpa = sbTotAuthByPpa;
		this.sbTotAuthByHa = sbTotAuthByHa;
		this.sbDispDateMonth = sbDispDateMonth;
		this.sbDispDateYear = sbDispDateYear;
		this.sbTotBasPrice = sbTotBasPrice;
		this.sbDiscount = sbDiscount;
		this.sbTotBasPriceZd = sbTotBasPriceZd;
		this.sbOopExp = sbOopExp;
		this.sbContAll = sbContAll;
		this.sbContCon = sbContCon;
		this.sbOxyCylMsk = sbOxyCylMsk;
		this.sbOxyExp = sbOxyExp;
		this.sbOxyAdj = sbOxyAdj;
		this.sbAdjVal = sbAdjVal;
		this.sbStProfFees = sbStProfFees;
		this.sbSpProfFees = sbSpProfFees;
		this.sbMpPfees = sbMpPfees;
		this.sbPfees2a = sbPfees2a;
		this.sbPfees2b = sbPfees2b;
		this.sbPfees2c = sbPfees2c;
		this.sbPfees2d = sbPfees2d;
		this.sbPfees2e = sbPfees2e;
		this.sbPfees2f = sbPfees2f;
		this.sbPfees2g = sbPfees2g;
		this.sbExpPrescFees = sbExpPrescFees;
		this.sbAddProfPay = sbAddProfPay;
		this.sbPrescChNew = sbPrescChNew;
		this.sbPrescChOld = sbPrescChOld;
		this.sbOtherAdj = sbOtherAdj;
		this.sbSubBpTotCalc = sbSubBpTotCalc;
		this.sbReimbTotCalc = sbReimbTotCalc;
		this.sbAddProfFees = sbAddProfFees;
		this.sbRemunTot = sbRemunTot;
		this.sbTotDed = sbTotDed;
		this.sbTotOfAcc = sbTotOfAcc;
		this.sbNetAmt = sbNetAmt;
		this.sbRecOfAdvCalc = sbRecOfAdvCalc;
		this.sbOthAdjAdv = sbOthAdjAdv;
		this.sbTotLaPay = sbTotLaPay;
		this.sbTotLaOther = sbTotLaOther;
		this.murNum = murNum;
		this.fp57NumForms = fp57NumForms;
		this.dispItemsNum = dispItemsNum;
		this.practicePayment = practicePayment;
		this.estabFee = estabFee;
		this.murFee = murFee;
		this.nmsFee = nmsFee;
		this.repeatSetup = repeatSetup;
		this.subTotalOfPrescFee = subTotalOfPrescFee;
		this.balDueRespOf = balDueRespOf;
		this.sbElhoseValue = sbElhoseValue;
		this.sbAvgItemValue = sbAvgItemValue;
		this.localPayLineId = localPayLineId;
		this.localPayLineDesc = localPayLineDesc;
		this.localPayLineValue = localPayLineValue;
		this.wgAeLineType = wgAeLineType;
		this.wgAeIdentifier = wgAeIdentifier;
		this.wgAeReasonCode = wgAeReasonCode;
		this.wgAeDescription = wgAeDescription;
		this.wgAeNumPxs = wgAeNumPxs;
		this.expItemsLimit2 = expItemsLimit2;
		this.expValueLimit2 = expValueLimit2;
		this.expItemsLimit1 = expItemsLimit1;
		this.expValueLimit1 = expValueLimit1;
		this.expTotItems = expTotItems;
		this.expTotValue = expTotValue;
		this.expensiveItemLine = expensiveItemLine;
		this.expItemDescription = expItemDescription;
		this.expItemPack = expItemPack;
		this.expItemQty = expItemQty;
		this.expItemValue = expItemValue;
		this.expensiveItemForm = expensiveItemForm;
		this.trlrBranchCount = trlrBranchCount;
		this.trlrTotalValue = trlrTotalValue;
		this.sbPfees2bHome = sbPfees2bHome;
		this.aurHomeFee = aurHomeFee;
		this.aurPremFee = aurPremFee;
		this.stomaCustValue = stomaCustValue;
		this.recAddAdvPay = recAddAdvPay;
		this.addAdvPay = addAdvPay;
		this.sbEtpForms = sbEtpForms;
		this.sbEtpItems = sbEtpItems;
		this.nmsNum = nmsNum;
		this.nmsItem = nmsItem;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "payment_date", nullable = false, length = 27)
	public Date getPaymentDate() {
		return this.paymentDate;
	}

	public void setPaymentDate(Date paymentDate) {
		this.paymentDate = paymentDate;
	}

	@Column(name = "cont_rate", nullable = false, precision = 53, scale = 0)
	public double getContRate() {
		return this.contRate;
	}

	public void setContRate(double contRate) {
		this.contRate = contRate;
	}

	@Column(name = "st_prof_fee", nullable = false, precision = 53, scale = 0)
	public double getStProfFee() {
		return this.stProfFee;
	}

	public void setStProfFee(double stProfFee) {
		this.stProfFee = stProfFee;
	}

	@Column(name = "sp_prof_fee", nullable = false, precision = 53, scale = 0)
	public double getSpProfFee() {
		return this.spProfFee;
	}

	public void setSpProfFee(double spProfFee) {
		this.spProfFee = spProfFee;
	}

	@Column(name = "exp_items_lower_limit", nullable = false)
	public short getExpItemsLowerLimit() {
		return this.expItemsLowerLimit;
	}

	public void setExpItemsLowerLimit(short expItemsLowerLimit) {
		this.expItemsLowerLimit = expItemsLowerLimit;
	}

	@Column(name = "exp_items_upper_limit", nullable = false)
	public short getExpItemsUpperLimit() {
		return this.expItemsUpperLimit;
	}

	public void setExpItemsUpperLimit(short expItemsUpperLimit) {
		this.expItemsUpperLimit = expItemsUpperLimit;
	}

	@Column(name = "mb_ocs_code", length = 30)
	public String getMbOcsCode() {
		return this.mbOcsCode;
	}

	public void setMbOcsCode(String mbOcsCode) {
		this.mbOcsCode = mbOcsCode;
	}

	@Column(name = "mb_cor_name", length = 50)
	public String getMbCorName() {
		return this.mbCorName;
	}

	public void setMbCorName(String mbCorName) {
		this.mbCorName = mbCorName;
	}

	@Column(name = "mb_shop_no", nullable = false)
	public short getMbShopNo() {
		return this.mbShopNo;
	}

	public void setMbShopNo(short mbShopNo) {
		this.mbShopNo = mbShopNo;
	}

	@Column(name = "mb_tradename", length = 50)
	public String getMbTradename() {
		return this.mbTradename;
	}

	public void setMbTradename(String mbTradename) {
		this.mbTradename = mbTradename;
	}

	@Column(name = "mb_cor_address1", length = 100)
	public String getMbCorAddress1() {
		return this.mbCorAddress1;
	}

	public void setMbCorAddress1(String mbCorAddress1) {
		this.mbCorAddress1 = mbCorAddress1;
	}

	@Column(name = "mb_cor_address2", length = 100)
	public String getMbCorAddress2() {
		return this.mbCorAddress2;
	}

	public void setMbCorAddress2(String mbCorAddress2) {
		this.mbCorAddress2 = mbCorAddress2;
	}

	@Column(name = "mb_cor_address3", length = 100)
	public String getMbCorAddress3() {
		return this.mbCorAddress3;
	}

	public void setMbCorAddress3(String mbCorAddress3) {
		this.mbCorAddress3 = mbCorAddress3;
	}

	@Column(name = "mb_cor_address4", length = 100)
	public String getMbCorAddress4() {
		return this.mbCorAddress4;
	}

	public void setMbCorAddress4(String mbCorAddress4) {
		this.mbCorAddress4 = mbCorAddress4;
	}

	@Column(name = "mb_cor_postcode", length = 10)
	public String getMbCorPostcode() {
		return this.mbCorPostcode;
	}

	public void setMbCorPostcode(String mbCorPostcode) {
		this.mbCorPostcode = mbCorPostcode;
	}

	@Column(name = "mb_name", length = 30)
	public String getMbName() {
		return this.mbName;
	}

	public void setMbName(String mbName) {
		this.mbName = mbName;
	}

	@Column(name = "mb_prem_add_1", length = 100)
	public String getMbPremAdd1() {
		return this.mbPremAdd1;
	}

	public void setMbPremAdd1(String mbPremAdd1) {
		this.mbPremAdd1 = mbPremAdd1;
	}

	@Column(name = "mb_prem_add_2", length = 100)
	public String getMbPremAdd2() {
		return this.mbPremAdd2;
	}

	public void setMbPremAdd2(String mbPremAdd2) {
		this.mbPremAdd2 = mbPremAdd2;
	}

	@Column(name = "mb_prem_add_3", length = 100)
	public String getMbPremAdd3() {
		return this.mbPremAdd3;
	}

	public void setMbPremAdd3(String mbPremAdd3) {
		this.mbPremAdd3 = mbPremAdd3;
	}

	@Column(name = "mb_prem_add_4", length = 100)
	public String getMbPremAdd4() {
		return this.mbPremAdd4;
	}

	public void setMbPremAdd4(String mbPremAdd4) {
		this.mbPremAdd4 = mbPremAdd4;
	}

	@Column(name = "mb_prem_pcode", length = 30)
	public String getMbPremPcode() {
		return this.mbPremPcode;
	}

	public void setMbPremPcode(String mbPremPcode) {
		this.mbPremPcode = mbPremPcode;
	}

	@Column(name = "mb_fhsa_code", length = 100)
	public String getMbFhsaCode() {
		return this.mbFhsaCode;
	}

	public void setMbFhsaCode(String mbFhsaCode) {
		this.mbFhsaCode = mbFhsaCode;
	}

	@Column(name = "mb_ppa_acc_code", length = 30)
	public String getMbPpaAccCode() {
		return this.mbPpaAccCode;
	}

	public void setMbPpaAccCode(String mbPpaAccCode) {
		this.mbPpaAccCode = mbPpaAccCode;
	}

	@Column(name = "mb_name_of_account", length = 50)
	public String getMbNameOfAccount() {
		return this.mbNameOfAccount;
	}

	public void setMbNameOfAccount(String mbNameOfAccount) {
		this.mbNameOfAccount = mbNameOfAccount;
	}

	@Column(name = "mb_bank_account_number", length = 50)
	public String getMbBankAccountNumber() {
		return this.mbBankAccountNumber;
	}

	public void setMbBankAccountNumber(String mbBankAccountNumber) {
		this.mbBankAccountNumber = mbBankAccountNumber;
	}

	@Column(name = "mb_building_soc_ref", length = 50)
	public String getMbBuildingSocRef() {
		return this.mbBuildingSocRef;
	}

	public void setMbBuildingSocRef(String mbBuildingSocRef) {
		this.mbBuildingSocRef = mbBuildingSocRef;
	}

	@Column(name = "mb_sort_code", length = 50)
	public String getMbSortCode() {
		return this.mbSortCode;
	}

	public void setMbSortCode(String mbSortCode) {
		this.mbSortCode = mbSortCode;
	}

	@Column(name = "mb_type_of_account", length = 50)
	public String getMbTypeOfAccount() {
		return this.mbTypeOfAccount;
	}

	public void setMbTypeOfAccount(String mbTypeOfAccount) {
		this.mbTypeOfAccount = mbTypeOfAccount;
	}

	@Column(name = "mb_payment_method", length = 50)
	public String getMbPaymentMethod() {
		return this.mbPaymentMethod;
	}

	public void setMbPaymentMethod(String mbPaymentMethod) {
		this.mbPaymentMethod = mbPaymentMethod;
	}

	@Column(name = "mb_payment", nullable = false, precision = 53, scale = 0)
	public double getMbPayment() {
		return this.mbPayment;
	}

	public void setMbPayment(double mbPayment) {
		this.mbPayment = mbPayment;
	}

	@Column(name = "mb_remit_disp_date", length = 30)
	public String getMbRemitDispDate() {
		return this.mbRemitDispDate;
	}

	public void setMbRemitDispDate(String mbRemitDispDate) {
		this.mbRemitDispDate = mbRemitDispDate;
	}

	@Column(name = "sb_300", length = 30)
	public String getSb300() {
		return this.sb300;
	}

	public void setSb300(String sb300) {
		this.sb300 = sb300;
	}

	@Column(name = "sb_mb_ocs_code", length = 30)
	public String getSbMbOcsCode() {
		return this.sbMbOcsCode;
	}

	public void setSbMbOcsCode(String sbMbOcsCode) {
		this.sbMbOcsCode = sbMbOcsCode;
	}

	@Column(name = "sb_ha_qcode", length = 10)
	public String getSbHaQcode() {
		return this.sbHaQcode;
	}

	public void setSbHaQcode(String sbHaQcode) {
		this.sbHaQcode = sbHaQcode;
	}

	@Column(name = "sb_ocs_code", length = 30)
	public String getSbOcsCode() {
		return this.sbOcsCode;
	}

	public void setSbOcsCode(String sbOcsCode) {
		this.sbOcsCode = sbOcsCode;
	}

	@Column(name = "sb_ta_name", length = 50)
	public String getSbTaName() {
		return this.sbTaName;
	}

	public void setSbTaName(String sbTaName) {
		this.sbTaName = sbTaName;
	}

	@Column(name = "sb_name", length = 50)
	public String getSbName() {
		return this.sbName;
	}

	public void setSbName(String sbName) {
		this.sbName = sbName;
	}

	@Column(name = "sb_address_1", length = 100)
	public String getSbAddress1() {
		return this.sbAddress1;
	}

	public void setSbAddress1(String sbAddress1) {
		this.sbAddress1 = sbAddress1;
	}

	@Column(name = "sb_address_2", length = 100)
	public String getSbAddress2() {
		return this.sbAddress2;
	}

	public void setSbAddress2(String sbAddress2) {
		this.sbAddress2 = sbAddress2;
	}

	@Column(name = "sb_address_3", length = 100)
	public String getSbAddress3() {
		return this.sbAddress3;
	}

	public void setSbAddress3(String sbAddress3) {
		this.sbAddress3 = sbAddress3;
	}

	@Column(name = "sb_address_post_code", length = 10)
	public String getSbAddressPostCode() {
		return this.sbAddressPostCode;
	}

	public void setSbAddressPostCode(String sbAddressPostCode) {
		this.sbAddressPostCode = sbAddressPostCode;
	}

	@Column(name = "sb_health_authority", length = 100)
	public String getSbHealthAuthority() {
		return this.sbHealthAuthority;
	}

	public void setSbHealthAuthority(String sbHealthAuthority) {
		this.sbHealthAuthority = sbHealthAuthority;
	}

	@Column(name = "sb_con_ppa_code", length = 30)
	public String getSbConPpaCode() {
		return this.sbConPpaCode;
	}

	public void setSbConPpaCode(String sbConPpaCode) {
		this.sbConPpaCode = sbConPpaCode;
	}

	@Column(name = "sb_con_la_line", length = 30)
	public String getSbConLaLine() {
		return this.sbConLaLine;
	}

	public void setSbConLaLine(String sbConLaLine) {
		this.sbConLaLine = sbConLaLine;
	}

	@Column(name = "sb_payment", nullable = false, precision = 53, scale = 0)
	public double getSbPayment() {
		return this.sbPayment;
	}

	public void setSbPayment(double sbPayment) {
		this.sbPayment = sbPayment;
	}

	@Column(name = "sb_con_forms_rec", nullable = false)
	public short getSbConFormsRec() {
		return this.sbConFormsRec;
	}

	public void setSbConFormsRec(short sbConFormsRec) {
		this.sbConFormsRec = sbConFormsRec;
	}

	@Column(name = "sb_con_items_sdr", nullable = false)
	public short getSbConItemsSdr() {
		return this.sbConItemsSdr;
	}

	public void setSbConItemsSdr(short sbConItemsSdr) {
		this.sbConItemsSdr = sbConItemsSdr;
	}

	@Column(name = "sb_con_items_zd", nullable = false)
	public short getSbConItemsZd() {
		return this.sbConItemsZd;
	}

	public void setSbConItemsZd(short sbConItemsZd) {
		this.sbConItemsZd = sbConItemsZd;
	}

	@Column(name = "sb_con_forms_rb", nullable = false)
	public short getSbConFormsRb() {
		return this.sbConFormsRb;
	}

	public void setSbConFormsRb(short sbConFormsRb) {
		this.sbConFormsRb = sbConFormsRb;
	}

	@Column(name = "sb_con_items_rb", nullable = false)
	public short getSbConItemsRb() {
		return this.sbConItemsRb;
	}

	public void setSbConItemsRb(short sbConItemsRb) {
		this.sbConItemsRb = sbConItemsRb;
	}

	@Column(name = "sb_con_disc", nullable = false, precision = 53, scale = 0)
	public double getSbConDisc() {
		return this.sbConDisc;
	}

	public void setSbConDisc(double sbConDisc) {
		this.sbConDisc = sbConDisc;
	}

	@Column(name = "sb_con_num_con_all", nullable = false)
	public short getSbConNumConAll() {
		return this.sbConNumConAll;
	}

	public void setSbConNumConAll(short sbConNumConAll) {
		this.sbConNumConAll = sbConNumConAll;
	}

	@Column(name = "sb_con_adj_text", length = 30)
	public String getSbConAdjText() {
		return this.sbConAdjText;
	}

	public void setSbConAdjText(String sbConAdjText) {
		this.sbConAdjText = sbConAdjText;
	}

	@Column(name = "sb_no_stpro_fees", nullable = false)
	public short getSbNoStproFees() {
		return this.sbNoStproFees;
	}

	public void setSbNoStproFees(short sbNoStproFees) {
		this.sbNoStproFees = sbNoStproFees;
	}

	@Column(name = "sb_no_sprof_fees", nullable = false)
	public short getSbNoSprofFees() {
		return this.sbNoSprofFees;
	}

	public void setSbNoSprofFees(short sbNoSprofFees) {
		this.sbNoSprofFees = sbNoSprofFees;
	}

	@Column(name = "sb_no_epresc_fees", nullable = false, precision = 53, scale = 0)
	public double getSbNoEprescFees() {
		return this.sbNoEprescFees;
	}

	public void setSbNoEprescFees(double sbNoEprescFees) {
		this.sbNoEprescFees = sbNoEprescFees;
	}

	@Column(name = "sb_recovery", nullable = false, precision = 53, scale = 0)
	public double getSbRecovery() {
		return this.sbRecovery;
	}

	public void setSbRecovery(double sbRecovery) {
		this.sbRecovery = sbRecovery;
	}

	@Column(name = "sb_no_presc_new", nullable = false)
	public short getSbNoPrescNew() {
		return this.sbNoPrescNew;
	}

	public void setSbNoPrescNew(short sbNoPrescNew) {
		this.sbNoPrescNew = sbNoPrescNew;
	}

	@Column(name = "sb_presc_rate_new", nullable = false, precision = 53, scale = 0)
	public double getSbPrescRateNew() {
		return this.sbPrescRateNew;
	}

	public void setSbPrescRateNew(double sbPrescRateNew) {
		this.sbPrescRateNew = sbPrescRateNew;
	}

	@Column(name = "sb_no_presc_old", nullable = false, precision = 53, scale = 0)
	public double getSbNoPrescOld() {
		return this.sbNoPrescOld;
	}

	public void setSbNoPrescOld(double sbNoPrescOld) {
		this.sbNoPrescOld = sbNoPrescOld;
	}

	@Column(name = "sb_presc_rate_old", nullable = false, precision = 53, scale = 0)
	public double getSbPrescRateOld() {
		return this.sbPrescRateOld;
	}

	public void setSbPrescRateOld(double sbPrescRateOld) {
		this.sbPrescRateOld = sbPrescRateOld;
	}

	@Column(name = "sb_adv_payment", nullable = false, precision = 53, scale = 0)
	public double getSbAdvPayment() {
		return this.sbAdvPayment;
	}

	public void setSbAdvPayment(double sbAdvPayment) {
		this.sbAdvPayment = sbAdvPayment;
	}

	@Column(name = "sb_adv_month", length = 30)
	public String getSbAdvMonth() {
		return this.sbAdvMonth;
	}

	public void setSbAdvMonth(String sbAdvMonth) {
		this.sbAdvMonth = sbAdvMonth;
	}

	@Column(name = "sb_adv_items", nullable = false)
	public short getSbAdvItems() {
		return this.sbAdvItems;
	}

	public void setSbAdvItems(short sbAdvItems) {
		this.sbAdvItems = sbAdvItems;
	}

	@Column(name = "sb_adv_chrg", nullable = false)
	public short getSbAdvChrg() {
		return this.sbAdvChrg;
	}

	public void setSbAdvChrg(short sbAdvChrg) {
		this.sbAdvChrg = sbAdvChrg;
	}

	@Column(name = "sb_other_adv_reason", length = 30)
	public String getSbOtherAdvReason() {
		return this.sbOtherAdvReason;
	}

	public void setSbOtherAdvReason(String sbOtherAdvReason) {
		this.sbOtherAdvReason = sbOtherAdvReason;
	}

	@Column(name = "sb_rec_of_adv_reason", length = 30)
	public String getSbRecOfAdvReason() {
		return this.sbRecOfAdvReason;
	}

	public void setSbRecOfAdvReason(String sbRecOfAdvReason) {
		this.sbRecOfAdvReason = sbRecOfAdvReason;
	}

	@Column(name = "sb_tot_auth_by_ppa", nullable = false, precision = 53, scale = 0)
	public double getSbTotAuthByPpa() {
		return this.sbTotAuthByPpa;
	}

	public void setSbTotAuthByPpa(double sbTotAuthByPpa) {
		this.sbTotAuthByPpa = sbTotAuthByPpa;
	}

	@Column(name = "sb_tot_auth_by_ha", nullable = false, precision = 53, scale = 0)
	public double getSbTotAuthByHa() {
		return this.sbTotAuthByHa;
	}

	public void setSbTotAuthByHa(double sbTotAuthByHa) {
		this.sbTotAuthByHa = sbTotAuthByHa;
	}

	@Column(name = "sb_disp_date_month", length = 30)
	public String getSbDispDateMonth() {
		return this.sbDispDateMonth;
	}

	public void setSbDispDateMonth(String sbDispDateMonth) {
		this.sbDispDateMonth = sbDispDateMonth;
	}

	@Column(name = "sb_disp_date_year", nullable = false)
	public short getSbDispDateYear() {
		return this.sbDispDateYear;
	}

	public void setSbDispDateYear(short sbDispDateYear) {
		this.sbDispDateYear = sbDispDateYear;
	}

	@Column(name = "sb_tot_bas_price", nullable = false, precision = 53, scale = 0)
	public double getSbTotBasPrice() {
		return this.sbTotBasPrice;
	}

	public void setSbTotBasPrice(double sbTotBasPrice) {
		this.sbTotBasPrice = sbTotBasPrice;
	}

	@Column(name = "sb_discount", nullable = false, precision = 53, scale = 0)
	public double getSbDiscount() {
		return this.sbDiscount;
	}

	public void setSbDiscount(double sbDiscount) {
		this.sbDiscount = sbDiscount;
	}

	@Column(name = "sb_tot_bas_price_zd", nullable = false, precision = 53, scale = 0)
	public double getSbTotBasPriceZd() {
		return this.sbTotBasPriceZd;
	}

	public void setSbTotBasPriceZd(double sbTotBasPriceZd) {
		this.sbTotBasPriceZd = sbTotBasPriceZd;
	}

	@Column(name = "sb_oop_exp", nullable = false, precision = 53, scale = 0)
	public double getSbOopExp() {
		return this.sbOopExp;
	}

	public void setSbOopExp(double sbOopExp) {
		this.sbOopExp = sbOopExp;
	}

	@Column(name = "sb_cont_all", nullable = false, precision = 53, scale = 0)
	public double getSbContAll() {
		return this.sbContAll;
	}

	public void setSbContAll(double sbContAll) {
		this.sbContAll = sbContAll;
	}

	@Column(name = "sb_cont_con", nullable = false, precision = 53, scale = 0)
	public double getSbContCon() {
		return this.sbContCon;
	}

	public void setSbContCon(double sbContCon) {
		this.sbContCon = sbContCon;
	}

	@Column(name = "sb_oxy_cyl_msk", nullable = false, precision = 53, scale = 0)
	public double getSbOxyCylMsk() {
		return this.sbOxyCylMsk;
	}

	public void setSbOxyCylMsk(double sbOxyCylMsk) {
		this.sbOxyCylMsk = sbOxyCylMsk;
	}

	@Column(name = "sb_oxy_exp", nullable = false, precision = 53, scale = 0)
	public double getSbOxyExp() {
		return this.sbOxyExp;
	}

	public void setSbOxyExp(double sbOxyExp) {
		this.sbOxyExp = sbOxyExp;
	}

	@Column(name = "sb_oxy_adj", nullable = false, precision = 53, scale = 0)
	public double getSbOxyAdj() {
		return this.sbOxyAdj;
	}

	public void setSbOxyAdj(double sbOxyAdj) {
		this.sbOxyAdj = sbOxyAdj;
	}

	@Column(name = "sb_adj_val", nullable = false, precision = 53, scale = 0)
	public double getSbAdjVal() {
		return this.sbAdjVal;
	}

	public void setSbAdjVal(double sbAdjVal) {
		this.sbAdjVal = sbAdjVal;
	}

	@Column(name = "sb_st_prof_fees", nullable = false, precision = 53, scale = 0)
	public double getSbStProfFees() {
		return this.sbStProfFees;
	}

	public void setSbStProfFees(double sbStProfFees) {
		this.sbStProfFees = sbStProfFees;
	}

	@Column(name = "sb_sp_prof_fees", nullable = false, precision = 53, scale = 0)
	public double getSbSpProfFees() {
		return this.sbSpProfFees;
	}

	public void setSbSpProfFees(double sbSpProfFees) {
		this.sbSpProfFees = sbSpProfFees;
	}

	@Column(name = "sb_mp_pfees", nullable = false, precision = 53, scale = 0)
	public double getSbMpPfees() {
		return this.sbMpPfees;
	}

	public void setSbMpPfees(double sbMpPfees) {
		this.sbMpPfees = sbMpPfees;
	}

	@Column(name = "sb_pfees_2a", nullable = false, precision = 53, scale = 0)
	public double getSbPfees2a() {
		return this.sbPfees2a;
	}

	public void setSbPfees2a(double sbPfees2a) {
		this.sbPfees2a = sbPfees2a;
	}

	@Column(name = "sb_pfees_2b", nullable = false, precision = 53, scale = 0)
	public double getSbPfees2b() {
		return this.sbPfees2b;
	}

	public void setSbPfees2b(double sbPfees2b) {
		this.sbPfees2b = sbPfees2b;
	}

	@Column(name = "sb_pfees_2c", nullable = false, precision = 53, scale = 0)
	public double getSbPfees2c() {
		return this.sbPfees2c;
	}

	public void setSbPfees2c(double sbPfees2c) {
		this.sbPfees2c = sbPfees2c;
	}

	@Column(name = "sb_pfees_2d", nullable = false, precision = 53, scale = 0)
	public double getSbPfees2d() {
		return this.sbPfees2d;
	}

	public void setSbPfees2d(double sbPfees2d) {
		this.sbPfees2d = sbPfees2d;
	}

	@Column(name = "sb_pfees_2e", nullable = false, precision = 53, scale = 0)
	public double getSbPfees2e() {
		return this.sbPfees2e;
	}

	public void setSbPfees2e(double sbPfees2e) {
		this.sbPfees2e = sbPfees2e;
	}

	@Column(name = "sb_pfees_2f", nullable = false, precision = 53, scale = 0)
	public double getSbPfees2f() {
		return this.sbPfees2f;
	}

	public void setSbPfees2f(double sbPfees2f) {
		this.sbPfees2f = sbPfees2f;
	}

	@Column(name = "sb_pfees_2g", nullable = false, precision = 53, scale = 0)
	public double getSbPfees2g() {
		return this.sbPfees2g;
	}

	public void setSbPfees2g(double sbPfees2g) {
		this.sbPfees2g = sbPfees2g;
	}

	@Column(name = "sb_exp_presc_fees", nullable = false, precision = 53, scale = 0)
	public double getSbExpPrescFees() {
		return this.sbExpPrescFees;
	}

	public void setSbExpPrescFees(double sbExpPrescFees) {
		this.sbExpPrescFees = sbExpPrescFees;
	}

	@Column(name = "sb_add_prof_pay", nullable = false, precision = 53, scale = 0)
	public double getSbAddProfPay() {
		return this.sbAddProfPay;
	}

	public void setSbAddProfPay(double sbAddProfPay) {
		this.sbAddProfPay = sbAddProfPay;
	}

	@Column(name = "sb_presc_ch_new", nullable = false, precision = 53, scale = 0)
	public double getSbPrescChNew() {
		return this.sbPrescChNew;
	}

	public void setSbPrescChNew(double sbPrescChNew) {
		this.sbPrescChNew = sbPrescChNew;
	}

	@Column(name = "sb_presc_ch_old", nullable = false, precision = 53, scale = 0)
	public double getSbPrescChOld() {
		return this.sbPrescChOld;
	}

	public void setSbPrescChOld(double sbPrescChOld) {
		this.sbPrescChOld = sbPrescChOld;
	}

	@Column(name = "sb_other_adj", nullable = false, precision = 53, scale = 0)
	public double getSbOtherAdj() {
		return this.sbOtherAdj;
	}

	public void setSbOtherAdj(double sbOtherAdj) {
		this.sbOtherAdj = sbOtherAdj;
	}

	@Column(name = "sb_sub_bp_tot_calc", nullable = false, precision = 53, scale = 0)
	public double getSbSubBpTotCalc() {
		return this.sbSubBpTotCalc;
	}

	public void setSbSubBpTotCalc(double sbSubBpTotCalc) {
		this.sbSubBpTotCalc = sbSubBpTotCalc;
	}

	@Column(name = "sb_reimb_tot_calc", nullable = false, precision = 53, scale = 0)
	public double getSbReimbTotCalc() {
		return this.sbReimbTotCalc;
	}

	public void setSbReimbTotCalc(double sbReimbTotCalc) {
		this.sbReimbTotCalc = sbReimbTotCalc;
	}

	@Column(name = "sb_add_prof_fees", nullable = false, precision = 53, scale = 0)
	public double getSbAddProfFees() {
		return this.sbAddProfFees;
	}

	public void setSbAddProfFees(double sbAddProfFees) {
		this.sbAddProfFees = sbAddProfFees;
	}

	@Column(name = "sb_remun_tot", nullable = false, precision = 53, scale = 0)
	public double getSbRemunTot() {
		return this.sbRemunTot;
	}

	public void setSbRemunTot(double sbRemunTot) {
		this.sbRemunTot = sbRemunTot;
	}

	@Column(name = "sb_tot_ded", nullable = false, precision = 53, scale = 0)
	public double getSbTotDed() {
		return this.sbTotDed;
	}

	public void setSbTotDed(double sbTotDed) {
		this.sbTotDed = sbTotDed;
	}

	@Column(name = "sb_tot_of_acc", nullable = false, precision = 53, scale = 0)
	public double getSbTotOfAcc() {
		return this.sbTotOfAcc;
	}

	public void setSbTotOfAcc(double sbTotOfAcc) {
		this.sbTotOfAcc = sbTotOfAcc;
	}

	@Column(name = "sb_net_amt", nullable = false, precision = 53, scale = 0)
	public double getSbNetAmt() {
		return this.sbNetAmt;
	}

	public void setSbNetAmt(double sbNetAmt) {
		this.sbNetAmt = sbNetAmt;
	}

	@Column(name = "sb_rec_of_adv_calc", nullable = false, precision = 53, scale = 0)
	public double getSbRecOfAdvCalc() {
		return this.sbRecOfAdvCalc;
	}

	public void setSbRecOfAdvCalc(double sbRecOfAdvCalc) {
		this.sbRecOfAdvCalc = sbRecOfAdvCalc;
	}

	@Column(name = "sb_oth_adj_adv", nullable = false, precision = 53, scale = 0)
	public double getSbOthAdjAdv() {
		return this.sbOthAdjAdv;
	}

	public void setSbOthAdjAdv(double sbOthAdjAdv) {
		this.sbOthAdjAdv = sbOthAdjAdv;
	}

	@Column(name = "sb_tot_la_pay", nullable = false, precision = 53, scale = 0)
	public double getSbTotLaPay() {
		return this.sbTotLaPay;
	}

	public void setSbTotLaPay(double sbTotLaPay) {
		this.sbTotLaPay = sbTotLaPay;
	}

	@Column(name = "sb_tot_la_other", nullable = false, precision = 53, scale = 0)
	public double getSbTotLaOther() {
		return this.sbTotLaOther;
	}

	public void setSbTotLaOther(double sbTotLaOther) {
		this.sbTotLaOther = sbTotLaOther;
	}

	@Column(name = "mur_num", nullable = false, precision = 53, scale = 0)
	public double getMurNum() {
		return this.murNum;
	}

	public void setMurNum(double murNum) {
		this.murNum = murNum;
	}

	@Column(name = "fp57_num_forms", nullable = false, precision = 53, scale = 0)
	public double getFp57NumForms() {
		return this.fp57NumForms;
	}

	public void setFp57NumForms(double fp57NumForms) {
		this.fp57NumForms = fp57NumForms;
	}

	@Column(name = "disp_items_num", nullable = false, precision = 53, scale = 0)
	public double getDispItemsNum() {
		return this.dispItemsNum;
	}

	public void setDispItemsNum(double dispItemsNum) {
		this.dispItemsNum = dispItemsNum;
	}

	@Column(name = "practice_payment", nullable = false, precision = 53, scale = 0)
	public double getPracticePayment() {
		return this.practicePayment;
	}

	public void setPracticePayment(double practicePayment) {
		this.practicePayment = practicePayment;
	}

	@Column(name = "estab_fee", nullable = false, precision = 53, scale = 0)
	public double getEstabFee() {
		return this.estabFee;
	}

	public void setEstabFee(double estabFee) {
		this.estabFee = estabFee;
	}

	@Column(name = "mur_fee", nullable = false, precision = 53, scale = 0)
	public double getMurFee() {
		return this.murFee;
	}

	public void setMurFee(double murFee) {
		this.murFee = murFee;
	}

	@Column(name = "nms_fee", nullable = false, precision = 53, scale = 0)
	public double getNmsFee() {
		return this.nmsFee;
	}

	public void setNmsFee(double nmsFee) {
		this.nmsFee = nmsFee;
	}

	@Column(name = "repeat_setup", nullable = false, precision = 53, scale = 0)
	public double getRepeatSetup() {
		return this.repeatSetup;
	}

	public void setRepeatSetup(double repeatSetup) {
		this.repeatSetup = repeatSetup;
	}

	@Column(name = "sub_total_of_presc_fee", nullable = false, precision = 53, scale = 0)
	public double getSubTotalOfPrescFee() {
		return this.subTotalOfPrescFee;
	}

	public void setSubTotalOfPrescFee(double subTotalOfPrescFee) {
		this.subTotalOfPrescFee = subTotalOfPrescFee;
	}

	@Column(name = "bal_due_resp_of", nullable = false, precision = 53, scale = 0)
	public double getBalDueRespOf() {
		return this.balDueRespOf;
	}

	public void setBalDueRespOf(double balDueRespOf) {
		this.balDueRespOf = balDueRespOf;
	}

	@Column(name = "sb_elhose_value", nullable = false, precision = 53, scale = 0)
	public double getSbElhoseValue() {
		return this.sbElhoseValue;
	}

	public void setSbElhoseValue(double sbElhoseValue) {
		this.sbElhoseValue = sbElhoseValue;
	}

	@Column(name = "sb_avg_item_value", nullable = false, precision = 53, scale = 0)
	public double getSbAvgItemValue() {
		return this.sbAvgItemValue;
	}

	public void setSbAvgItemValue(double sbAvgItemValue) {
		this.sbAvgItemValue = sbAvgItemValue;
	}

	@Column(name = "local_pay_line_id", nullable = false)
	public short getLocalPayLineId() {
		return this.localPayLineId;
	}

	public void setLocalPayLineId(short localPayLineId) {
		this.localPayLineId = localPayLineId;
	}

	@Column(name = "local_pay_line_desc", length = 50)
	public String getLocalPayLineDesc() {
		return this.localPayLineDesc;
	}

	public void setLocalPayLineDesc(String localPayLineDesc) {
		this.localPayLineDesc = localPayLineDesc;
	}

	@Column(name = "local_pay_line_value", nullable = false, precision = 53, scale = 0)
	public double getLocalPayLineValue() {
		return this.localPayLineValue;
	}

	public void setLocalPayLineValue(double localPayLineValue) {
		this.localPayLineValue = localPayLineValue;
	}

	@Column(name = "wg_ae_line_type")
	public short getWgAeLineType() {
		return this.wgAeLineType;
	}

	public void setWgAeLineType(short wgAeLineType) {
		this.wgAeLineType = wgAeLineType;
	}

	@Column(name = "wg_ae_identifier", length = 10)
	public String getWgAeIdentifier() {
		return this.wgAeIdentifier;
	}

	public void setWgAeIdentifier(String wgAeIdentifier) {
		this.wgAeIdentifier = wgAeIdentifier;
	}

	@Column(name = "wg_ae_reason_code", length = 30)
	public String getWgAeReasonCode() {
		return this.wgAeReasonCode;
	}

	public void setWgAeReasonCode(String wgAeReasonCode) {
		this.wgAeReasonCode = wgAeReasonCode;
	}

	@Column(name = "wg_ae_description", length = 50)
	public String getWgAeDescription() {
		return this.wgAeDescription;
	}

	public void setWgAeDescription(String wgAeDescription) {
		this.wgAeDescription = wgAeDescription;
	}

	@Column(name = "wg_ae_num_pxs")
	public short getWgAeNumPxs() {
		return this.wgAeNumPxs;
	}

	public void setWgAeNumPxs(short wgAeNumPxs) {
		this.wgAeNumPxs = wgAeNumPxs;
	}

	@Column(name = "exp_items_limit2")
	public short getExpItemsLimit2() {
		return this.expItemsLimit2;
	}

	public void setExpItemsLimit2(short expItemsLimit2) {
		this.expItemsLimit2 = expItemsLimit2;
	}

	@Column(name = "exp_value_limit2", nullable = false, precision = 53, scale = 0)
	public double getExpValueLimit2() {
		return this.expValueLimit2;
	}

	public void setExpValueLimit2(double expValueLimit2) {
		this.expValueLimit2 = expValueLimit2;
	}

	@Column(name = "exp_items_limit1")
	public short getExpItemsLimit1() {
		return this.expItemsLimit1;
	}

	public void setExpItemsLimit1(short expItemsLimit1) {
		this.expItemsLimit1 = expItemsLimit1;
	}

	@Column(name = "exp_value_limit1", nullable = false, precision = 53, scale = 0)
	public double getExpValueLimit1() {
		return this.expValueLimit1;
	}

	public void setExpValueLimit1(double expValueLimit1) {
		this.expValueLimit1 = expValueLimit1;
	}

	@Column(name = "exp_tot_items")
	public short getExpTotItems() {
		return this.expTotItems;
	}

	public void setExpTotItems(short expTotItems) {
		this.expTotItems = expTotItems;
	}

	@Column(name = "exp_tot_value", nullable = false, precision = 53, scale = 0)
	public double getExpTotValue() {
		return this.expTotValue;
	}

	public void setExpTotValue(double expTotValue) {
		this.expTotValue = expTotValue;
	}

	@Column(name = "expensive_item_line", length = 10)
	public String getExpensiveItemLine() {
		return this.expensiveItemLine;
	}

	public void setExpensiveItemLine(String expensiveItemLine) {
		this.expensiveItemLine = expensiveItemLine;
	}

	@Column(name = "exp_item_description", length = 50)
	public String getExpItemDescription() {
		return this.expItemDescription;
	}

	public void setExpItemDescription(String expItemDescription) {
		this.expItemDescription = expItemDescription;
	}

	@Column(name = "exp_item_pack", nullable = false, precision = 53, scale = 0)
	public double getExpItemPack() {
		return this.expItemPack;
	}

	public void setExpItemPack(double expItemPack) {
		this.expItemPack = expItemPack;
	}

	@Column(name = "exp_item_qty")
	public short getExpItemQty() {
		return this.expItemQty;
	}

	public void setExpItemQty(short expItemQty) {
		this.expItemQty = expItemQty;
	}

	@Column(name = "exp_item_value", nullable = false, precision = 53, scale = 0)
	public double getExpItemValue() {
		return this.expItemValue;
	}

	public void setExpItemValue(double expItemValue) {
		this.expItemValue = expItemValue;
	}

	@Column(name = "expensive_item_form")
	public short getExpensiveItemForm() {
		return this.expensiveItemForm;
	}

	public void setExpensiveItemForm(short expensiveItemForm) {
		this.expensiveItemForm = expensiveItemForm;
	}

	@Column(name = "trlr_branch_count")
	public short getTrlrBranchCount() {
		return this.trlrBranchCount;
	}

	public void setTrlrBranchCount(short trlrBranchCount) {
		this.trlrBranchCount = trlrBranchCount;
	}

	@Column(name = "trlr_total_value", nullable = false, precision = 53, scale = 0)
	public double getTrlrTotalValue() {
		return this.trlrTotalValue;
	}

	public void setTrlrTotalValue(double trlrTotalValue) {
		this.trlrTotalValue = trlrTotalValue;
	}

	@Column(name = "sb_pfees_2b_home", nullable = false, precision = 53, scale = 0)
	public double getSbPfees2bHome() {
		return this.sbPfees2bHome;
	}

	public void setSbPfees2bHome(double sbPfees2bHome) {
		this.sbPfees2bHome = sbPfees2bHome;
	}

	@Column(name = "aur_home_fee", nullable = false, precision = 53, scale = 0)
	public double getAurHomeFee() {
		return this.aurHomeFee;
	}

	public void setAurHomeFee(double aurHomeFee) {
		this.aurHomeFee = aurHomeFee;
	}

	@Column(name = "aur_prem_fee", nullable = false, precision = 53, scale = 0)
	public double getAurPremFee() {
		return this.aurPremFee;
	}

	public void setAurPremFee(double aurPremFee) {
		this.aurPremFee = aurPremFee;
	}

	@Column(name = "stoma_cust_value", nullable = false, precision = 53, scale = 0)
	public double getStomaCustValue() {
		return this.stomaCustValue;
	}

	public void setStomaCustValue(double stomaCustValue) {
		this.stomaCustValue = stomaCustValue;
	}

	@Column(name = "rec_add_adv_pay", nullable = false, precision = 53, scale = 0)
	public double getRecAddAdvPay() {
		return this.recAddAdvPay;
	}

	public void setRecAddAdvPay(double recAddAdvPay) {
		this.recAddAdvPay = recAddAdvPay;
	}

	@Column(name = "add_adv_pay", nullable = false, precision = 53, scale = 0)
	public double getAddAdvPay() {
		return this.addAdvPay;
	}

	public void setAddAdvPay(double addAdvPay) {
		this.addAdvPay = addAdvPay;
	}

	@Column(name = "sb_etp_forms")
	public short getSbEtpForms() {
		return this.sbEtpForms;
	}

	public void setSbEtpForms(short sbEtpForms) {
		this.sbEtpForms = sbEtpForms;
	}

	@Column(name = "sb_etp_items", nullable = false, precision = 53, scale = 0)
	public double getSbEtpItems() {
		return this.sbEtpItems;
	}

	public void setSbEtpItems(double sbEtpItems) {
		this.sbEtpItems = sbEtpItems;
	}

	@Column(name = "nms_num", nullable = false, precision = 53, scale = 0)
	public double getNmsNum() {
		return this.nmsNum;
	}

	public void setNmsNum(double nmsNum) {
		this.nmsNum = nmsNum;
	}

	@Column(name = "nms_item")
	public short getNmsItem() {
		return this.nmsItem;
	}

	public void setNmsItem(short nmsItem) {
		this.nmsItem = nmsItem;
	}

	@Column(name = "created_by", nullable = false, length = 30)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 27)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "updated_by", length = 30)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", nullable = false, length = 27)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

}
