package com.avee.form;
// Generated 30-Mar-2018 12:11:34 by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;

/**
 * Ppa500 generated by hbm2java
 */

public class Ppa500 implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private int id;
	private Date paymentDate;
	private String sbOcsCode;
	private String mbTradename;
	private String sbConLaLine;
	private Short localPayLineId;
	private String localPayLineDesc;
	private Double localPayLineValue;

	public Ppa500() {
	}

	public Ppa500(int id, Date paymentDate) {
		this.id = id;
		this.paymentDate = paymentDate;
	}

	public Ppa500(int id, Date paymentDate, String sbOcsCode, String mbTradename, String sbConLaLine,
			Short localPayLineId, String localPayLineDesc, Double localPayLineValue) {
		this.id = id;
		this.paymentDate = paymentDate;
		this.sbOcsCode = sbOcsCode;
		this.mbTradename = mbTradename;
		this.sbConLaLine = sbConLaLine;
		this.localPayLineId = localPayLineId;
		this.localPayLineDesc = localPayLineDesc;
		this.localPayLineValue = localPayLineValue;
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Date getPaymentDate() {
		return paymentDate;
	}

	public void setPaymentDate(Date paymentDate) {
		this.paymentDate = paymentDate;
	}

	public String getSbOcsCode() {
		return sbOcsCode;
	}

	public void setSbOcsCode(String sbOcsCode) {
		this.sbOcsCode = sbOcsCode;
	}

	public String getMbTradename() {
		return mbTradename;
	}

	public void setMbTradename(String mbTradename) {
		this.mbTradename = mbTradename;
	}

	public String getSbConLaLine() {
		return sbConLaLine;
	}

	public void setSbConLaLine(String sbConLaLine) {
		this.sbConLaLine = sbConLaLine;
	}

	public Short getLocalPayLineId() {
		return localPayLineId;
	}

	public void setLocalPayLineId(Short localPayLineId) {
		this.localPayLineId = localPayLineId;
	}

	public String getLocalPayLineDesc() {
		return localPayLineDesc;
	}

	public void setLocalPayLineDesc(String localPayLineDesc) {
		this.localPayLineDesc = localPayLineDesc;
	}

	public Double getLocalPayLineValue() {
		return localPayLineValue;
	}

	public void setLocalPayLineValue(Double localPayLineValue) {
		this.localPayLineValue = localPayLineValue;
	}


}
