// default package
// Generated 30-Mar-2018 12:11:34 by Hibernate Tools 5.1.0.Alpha1
package com.avee.form;

/**
 * PpaBranchCodeDetails generated by hbm2java
 */

public class PpaBranchCodeDetails implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private int id;
	private String branchCode;
	private String branchName;
	private String branchDesc;

	public PpaBranchCodeDetails() {
	}

	public PpaBranchCodeDetails(int id) {
		this.id = id;
	}

	public PpaBranchCodeDetails(int id, String branchCode, String branchName, String branchDesc) {
		this.id = id;
		this.branchCode = branchCode;
		this.branchName = branchName;
		this.branchDesc = branchDesc;
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getBranchCode() {
		return branchCode;
	}

	public void setBranchCode(String branchCode) {
		this.branchCode = branchCode;
	}

	public String getBranchName() {
		return branchName;
	}

	public void setBranchName(String branchName) {
		this.branchName = branchName;
	}

	public String getBranchDesc() {
		return branchDesc;
	}

	public void setBranchDesc(String branchDesc) {
		this.branchDesc = branchDesc;
	}

	

}
