// default package
// Generated 30-Mar-2018 14:11:20 by Hibernate Tools 5.1.0.Alpha1
package com.avee.form;

import java.util.Date;

/**
 * PpaData generated by hbm2java
 */

public class PpaData implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private int id;
	private Date paymentDate;
	private double contRate;
	private double stProfFee;
	private double spProfFee;
	private short expItemsLowerLimit;
	private short expItemsUpperLimit;
	private String mbHaQcode;
	private String mbOcsCode;
	private String mbCorName;
	private short mbShopNo;
	private String mbTradename;
	private String mbCorAddress1;
	private String mbCorAddress2;
	private String mbCorAddress3;
	private String mbCorAddress4;
	private String mbCorPostcode;
	private String mbName;
	private String mbPremAdd1;
	private String mbPremAdd2;
	private String mbPremAdd3;
	private String mbPremAdd4;
	private String mbPremPcode;
	private String mbFhsaCode;
	private String mbPpaAccCode;
	private String mbNameOfAccount;
	private String mbBankAccountNumber;
	private String mbBuildingSocRef;
	private String mbSortCode;
	private String mbTypeOfAccount;
	private String mbPaymentMethod;
	private double mbPayment;
	private String mbRemitDispDate;
	private String sb300;
	private String sbMbOcsCode;
	private String sbHaQcode;
	private String sbOcsCode;
	private String sbTaName;
	private String sbName;
	private String sbAddress1;
	private String sbAddress2;
	private String sbAddress3;
	private String sbAddressPostCode;
	private String sbHealthAuthority;
	private String sbConPpaCode;
	private String sbConLaLine;
	private double sbPayment;
	private short sbConFormsRec;
	private short sbConItemsSdr;
	private short sbConItemsZd;
	private short sbConFormsRb;
	private short sbConItemsRb;
	private double sbConDisc;
	private short sbConNumConAll;
	private String sbConAdjText;
	private short sbNoStproFees;
	private short sbNoSprofFees;
	private double sbNoEprescFees;
	private double sbRecovery;
	private short sbNoPrescNew;
	private double sbPrescRateNew;
	private double sbNoPrescOld;
	private double sbPrescRateOld;
	private double sbAdvPayment;
	private String sbAdvMonth;
	private short sbAdvItems;
	private short sbAdvChrg;
	private String sbOtherAdvReason;
	private String sbRecOfAdvReason;
	private double sbTotAuthByPpa;
	private double sbTotAuthByHa;
	private String sbDispDateMonth;
	private short sbDispDateYear;
	private double sbTotBasPrice;
	private double sbDiscount;
	private double sbTotBasPriceZd;
	private double sbOopExp;
	private double sbContAll;
	private double sbContCon;
	private double sbOxyCylMsk;
	private double sbOxyExp;
	private double sbOxyAdj;
	private double sbAdjVal;
	private double sbStProfFees;
	private double sbSpProfFees;
	private double sbMpPfees;
	private double sbPfees2a;
	private double sbPfees2b;
	private double sbPfees2c;
	private double sbPfees2d;
	private double sbPfees2e;
	private double sbPfees2f;
	private double sbPfees2g;
	private double sbExpPrescFees;
	private double sbAddProfPay;
	private double sbPrescChNew;
	private double sbPrescChOld;
	private double sbOtherAdj;
	private double sbSubBpTotCalc;
	private double sbReimbTotCalc;
	private double sbAddProfFees;
	private double sbRemunTot;
	private double sbTotDed;
	private double sbTotOfAcc;
	private double sbNetAmt;
	private double sbRecOfAdvCalc;
	private double sbOthAdjAdv;
	private double sbTotLaPay;
	private double sbTotLaOther;
	private double murNum;
	private double fp57NumForms;
	private double dispItemsNum;
	private double practicePayment;
	private double estabFee;
	private double murFee;
	private double nmsFee;
	private double repeatSetup;
	private double subTotalOfPrescFee;
	private double balDueRespOf;
	private double sbElhoseValue;
	private double sbAvgItemValue;
	private short localPayLineId;
	private String localPayLineDesc;
	private double localPayLineValue;
	private short wgAeLineType;
	private String wgAeIdentifier;
	private String wgAeReasonCode;
	private String wgAeDescription;
	private short wgAeNumPxs;
	private short expItemsLimit2;
	private double expValueLimit2;
	private short expItemsLimit1;
	private double expValueLimit1;
	private short expTotItems;
	private double expTotValue;
	private String expensiveItemLine;
	private String expItemDescription;
	private double expItemPack;
	private short expItemQty;
	private double expItemValue;
	private short expensiveItemForm;
	private short trlrBranchCount;
	private double trlrTotalValue;
	private double sbPfees2bHome;
	private double aurHomeFee;
	private double aurPremFee;
	private double stomaCustValue;
	private double recAddAdvPay;
	private double addAdvPay;
	private short sbEtpForms;
	private double sbEtpItems;
	private double nmsNum;
	private short nmsItem;
	private double mPayment;
	private String createdBy;
	private Date createdDate;
	private String updatedBy;
	private Date updatedDate;

	public PpaData() {
	}

	public PpaData(int id, Date paymentDate, double contRate, double stProfFee, double spProfFee,
			short expItemsLowerLimit, short expItemsUpperLimit, short mbShopNo, double mbPayment, double sbPayment,
			short sbConFormsRec, short sbConItemsSdr, short sbConItemsZd, short sbConFormsRb, short sbConItemsRb,
			double sbConDisc, short sbConNumConAll, short sbNoStproFees, short sbNoSprofFees, double sbNoEprescFees,
			double sbRecovery, short sbNoPrescNew, double sbPrescRateNew, double sbNoPrescOld, double sbPrescRateOld,
			double sbAdvPayment, short sbAdvItems, short sbAdvChrg, double sbTotAuthByPpa, double sbTotAuthByHa,
			short sbDispDateYear, double sbTotBasPrice, double sbDiscount, double sbTotBasPriceZd, double sbOopExp,
			double sbContAll, double sbContCon, double sbOxyCylMsk, double sbOxyExp, double sbOxyAdj, double sbAdjVal,
			double sbStProfFees, double sbSpProfFees, double sbMpPfees, double sbPfees2a, double sbPfees2b,
			double sbPfees2c, double sbPfees2d, double sbPfees2e, double sbPfees2f, double sbPfees2g,
			double sbExpPrescFees, double sbAddProfPay, double sbPrescChNew, double sbPrescChOld, double sbOtherAdj,
			double sbSubBpTotCalc, double sbReimbTotCalc, double sbAddProfFees, double sbRemunTot, double sbTotDed,
			double sbTotOfAcc, double sbNetAmt, double sbRecOfAdvCalc, double sbOthAdjAdv, double sbTotLaPay,
			double sbTotLaOther, double murNum, double fp57NumForms, double dispItemsNum, double practicePayment,
			double estabFee, double murFee, double nmsFee, double repeatSetup, double subTotalOfPrescFee,
			double balDueRespOf, double sbElhoseValue, double sbAvgItemValue, short localPayLineId,
			double localPayLineValue, double expValueLimit2, double expValueLimit1, double expTotValue,
			double expItemPack, double expItemValue, double trlrTotalValue, double sbPfees2bHome, double aurHomeFee,
			double aurPremFee, double stomaCustValue, double recAddAdvPay, double addAdvPay, double sbEtpItems,
			double nmsNum, String createdBy, Date createdDate, Date updatedDate,double mPayment) {
		this.id = id;
		this.paymentDate = paymentDate;
		this.contRate = contRate;
		this.stProfFee = stProfFee;
		this.spProfFee = spProfFee;
		this.expItemsLowerLimit = expItemsLowerLimit;
		this.expItemsUpperLimit = expItemsUpperLimit;
		this.mbShopNo = mbShopNo;
		this.mbPayment = mbPayment;
		this.sbPayment = sbPayment;
		this.sbConFormsRec = sbConFormsRec;
		this.sbConItemsSdr = sbConItemsSdr;
		this.sbConItemsZd = sbConItemsZd;
		this.sbConFormsRb = sbConFormsRb;
		this.sbConItemsRb = sbConItemsRb;
		this.sbConDisc = sbConDisc;
		this.sbConNumConAll = sbConNumConAll;
		this.sbNoStproFees = sbNoStproFees;
		this.sbNoSprofFees = sbNoSprofFees;
		this.sbNoEprescFees = sbNoEprescFees;
		this.sbRecovery = sbRecovery;
		this.sbNoPrescNew = sbNoPrescNew;
		this.sbPrescRateNew = sbPrescRateNew;
		this.sbNoPrescOld = sbNoPrescOld;
		this.sbPrescRateOld = sbPrescRateOld;
		this.sbAdvPayment = sbAdvPayment;
		this.sbAdvItems = sbAdvItems;
		this.sbAdvChrg = sbAdvChrg;
		this.sbTotAuthByPpa = sbTotAuthByPpa;
		this.sbTotAuthByHa = sbTotAuthByHa;
		this.sbDispDateYear = sbDispDateYear;
		this.sbTotBasPrice = sbTotBasPrice;
		this.sbDiscount = sbDiscount;
		this.sbTotBasPriceZd = sbTotBasPriceZd;
		this.sbOopExp = sbOopExp;
		this.sbContAll = sbContAll;
		this.sbContCon = sbContCon;
		this.sbOxyCylMsk = sbOxyCylMsk;
		this.sbOxyExp = sbOxyExp;
		this.sbOxyAdj = sbOxyAdj;
		this.sbAdjVal = sbAdjVal;
		this.sbStProfFees = sbStProfFees;
		this.sbSpProfFees = sbSpProfFees;
		this.sbMpPfees = sbMpPfees;
		this.sbPfees2a = sbPfees2a;
		this.sbPfees2b = sbPfees2b;
		this.sbPfees2c = sbPfees2c;
		this.sbPfees2d = sbPfees2d;
		this.sbPfees2e = sbPfees2e;
		this.sbPfees2f = sbPfees2f;
		this.sbPfees2g = sbPfees2g;
		this.sbExpPrescFees = sbExpPrescFees;
		this.sbAddProfPay = sbAddProfPay;
		this.sbPrescChNew = sbPrescChNew;
		this.sbPrescChOld = sbPrescChOld;
		this.sbOtherAdj = sbOtherAdj;
		this.sbSubBpTotCalc = sbSubBpTotCalc;
		this.sbReimbTotCalc = sbReimbTotCalc;
		this.sbAddProfFees = sbAddProfFees;
		this.sbRemunTot = sbRemunTot;
		this.sbTotDed = sbTotDed;
		this.sbTotOfAcc = sbTotOfAcc;
		this.sbNetAmt = sbNetAmt;
		this.sbRecOfAdvCalc = sbRecOfAdvCalc;
		this.sbOthAdjAdv = sbOthAdjAdv;
		this.sbTotLaPay = sbTotLaPay;
		this.sbTotLaOther = sbTotLaOther;
		this.murNum = murNum;
		this.fp57NumForms = fp57NumForms;
		this.dispItemsNum = dispItemsNum;
		this.practicePayment = practicePayment;
		this.estabFee = estabFee;
		this.murFee = murFee;
		this.nmsFee = nmsFee;
		this.repeatSetup = repeatSetup;
		this.subTotalOfPrescFee = subTotalOfPrescFee;
		this.balDueRespOf = balDueRespOf;
		this.sbElhoseValue = sbElhoseValue;
		this.sbAvgItemValue = sbAvgItemValue;
		this.localPayLineId = localPayLineId;
		this.localPayLineValue = localPayLineValue;
		this.expValueLimit2 = expValueLimit2;
		this.expValueLimit1 = expValueLimit1;
		this.expTotValue = expTotValue;
		this.expItemPack = expItemPack;
		this.expItemValue = expItemValue;
		this.trlrTotalValue = trlrTotalValue;
		this.sbPfees2bHome = sbPfees2bHome;
		this.aurHomeFee = aurHomeFee;
		this.aurPremFee = aurPremFee;
		this.stomaCustValue = stomaCustValue;
		this.recAddAdvPay = recAddAdvPay;
		this.addAdvPay = addAdvPay;
		this.sbEtpItems = sbEtpItems;
		this.nmsNum = nmsNum;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.mPayment=mPayment;
	}

	public PpaData(int id, Date paymentDate, double contRate, double stProfFee, double spProfFee,
			short expItemsLowerLimit, short expItemsUpperLimit, String mbHaQcode, String mbOcsCode, String mbCorName,
			short mbShopNo, String mbTradename, String mbCorAddress1, String mbCorAddress2, String mbCorAddress3,
			String mbCorAddress4, String mbCorPostcode, String mbName, String mbPremAdd1, String mbPremAdd2,
			String mbPremAdd3, String mbPremAdd4, String mbPremPcode, String mbFhsaCode, String mbPpaAccCode,
			String mbNameOfAccount, String mbBankAccountNumber, String mbBuildingSocRef, String mbSortCode,
			String mbTypeOfAccount, String mbPaymentMethod, double mbPayment, String mbRemitDispDate, String sb300,
			String sbMbOcsCode, String sbHaQcode, String sbOcsCode, String sbTaName, String sbName, String sbAddress1,
			String sbAddress2, String sbAddress3, String sbAddressPostCode, String sbHealthAuthority,
			String sbConPpaCode, String sbConLaLine, double sbPayment, short sbConFormsRec, short sbConItemsSdr,
			short sbConItemsZd, short sbConFormsRb, short sbConItemsRb, double sbConDisc, short sbConNumConAll,
			String sbConAdjText, short sbNoStproFees, short sbNoSprofFees, double sbNoEprescFees, double sbRecovery,
			short sbNoPrescNew, double sbPrescRateNew, double sbNoPrescOld, double sbPrescRateOld, double sbAdvPayment,
			String sbAdvMonth, short sbAdvItems, short sbAdvChrg, String sbOtherAdvReason, String sbRecOfAdvReason,
			double sbTotAuthByPpa, double sbTotAuthByHa, String sbDispDateMonth, short sbDispDateYear,
			double sbTotBasPrice, double sbDiscount, double sbTotBasPriceZd, double sbOopExp, double sbContAll,
			double sbContCon, double sbOxyCylMsk, double sbOxyExp, double sbOxyAdj, double sbAdjVal,
			double sbStProfFees, double sbSpProfFees, double sbMpPfees, double sbPfees2a, double sbPfees2b,
			double sbPfees2c, double sbPfees2d, double sbPfees2e, double sbPfees2f, double sbPfees2g,
			double sbExpPrescFees, double sbAddProfPay, double sbPrescChNew, double sbPrescChOld, double sbOtherAdj,
			double sbSubBpTotCalc, double sbReimbTotCalc, double sbAddProfFees, double sbRemunTot, double sbTotDed,
			double sbTotOfAcc, double sbNetAmt, double sbRecOfAdvCalc, double sbOthAdjAdv, double sbTotLaPay,
			double sbTotLaOther, double murNum, double fp57NumForms, double dispItemsNum, double practicePayment,
			double estabFee, double murFee, double nmsFee, double repeatSetup, double subTotalOfPrescFee,
			double balDueRespOf, double sbElhoseValue, double sbAvgItemValue, short localPayLineId,
			String localPayLineDesc, double localPayLineValue, short wgAeLineType, String wgAeIdentifier,
			String wgAeReasonCode, String wgAeDescription, short wgAeNumPxs, short expItemsLimit2,
			double expValueLimit2, short expItemsLimit1, double expValueLimit1, short expTotItems, double expTotValue,
			String expensiveItemLine, String expItemDescription, double expItemPack, short expItemQty,
			double expItemValue, short expensiveItemForm, short trlrBranchCount, double trlrTotalValue,
			double sbPfees2bHome, double aurHomeFee, double aurPremFee, double stomaCustValue, double recAddAdvPay,
			double addAdvPay, short sbEtpForms, double sbEtpItems, double nmsNum, short nmsItem, String createdBy,
			Date createdDate, String updatedBy, Date updatedDate ,double mPayment) {
		super();
		this.id = id;
		this.paymentDate = paymentDate;
		this.contRate = contRate;
		this.stProfFee = stProfFee;
		this.spProfFee = spProfFee;
		this.expItemsLowerLimit = expItemsLowerLimit;
		this.expItemsUpperLimit = expItemsUpperLimit;
		this.mbHaQcode = mbHaQcode;
		this.mbOcsCode = mbOcsCode;
		this.mbCorName = mbCorName;
		this.mbShopNo = mbShopNo;
		this.mbTradename = mbTradename;
		this.mbCorAddress1 = mbCorAddress1;
		this.mbCorAddress2 = mbCorAddress2;
		this.mbCorAddress3 = mbCorAddress3;
		this.mbCorAddress4 = mbCorAddress4;
		this.mbCorPostcode = mbCorPostcode;
		this.mbName = mbName;
		this.mbPremAdd1 = mbPremAdd1;
		this.mbPremAdd2 = mbPremAdd2;
		this.mbPremAdd3 = mbPremAdd3;
		this.mbPremAdd4 = mbPremAdd4;
		this.mbPremPcode = mbPremPcode;
		this.mbFhsaCode = mbFhsaCode;
		this.mbPpaAccCode = mbPpaAccCode;
		this.mbNameOfAccount = mbNameOfAccount;
		this.mbBankAccountNumber = mbBankAccountNumber;
		this.mbBuildingSocRef = mbBuildingSocRef;
		this.mbSortCode = mbSortCode;
		this.mbTypeOfAccount = mbTypeOfAccount;
		this.mbPaymentMethod = mbPaymentMethod;
		this.mbPayment = mbPayment;
		this.mbRemitDispDate = mbRemitDispDate;
		this.sb300 = sb300;
		this.sbMbOcsCode = sbMbOcsCode;
		this.sbHaQcode = sbHaQcode;
		this.sbOcsCode = sbOcsCode;
		this.sbTaName = sbTaName;
		this.sbName = sbName;
		this.sbAddress1 = sbAddress1;
		this.sbAddress2 = sbAddress2;
		this.sbAddress3 = sbAddress3;
		this.sbAddressPostCode = sbAddressPostCode;
		this.sbHealthAuthority = sbHealthAuthority;
		this.sbConPpaCode = sbConPpaCode;
		this.sbConLaLine = sbConLaLine;
		this.sbPayment = sbPayment;
		this.sbConFormsRec = sbConFormsRec;
		this.sbConItemsSdr = sbConItemsSdr;
		this.sbConItemsZd = sbConItemsZd;
		this.sbConFormsRb = sbConFormsRb;
		this.sbConItemsRb = sbConItemsRb;
		this.sbConDisc = sbConDisc;
		this.sbConNumConAll = sbConNumConAll;
		this.sbConAdjText = sbConAdjText;
		this.sbNoStproFees = sbNoStproFees;
		this.sbNoSprofFees = sbNoSprofFees;
		this.sbNoEprescFees = sbNoEprescFees;
		this.sbRecovery = sbRecovery;
		this.sbNoPrescNew = sbNoPrescNew;
		this.sbPrescRateNew = sbPrescRateNew;
		this.sbNoPrescOld = sbNoPrescOld;
		this.sbPrescRateOld = sbPrescRateOld;
		this.sbAdvPayment = sbAdvPayment;
		this.sbAdvMonth = sbAdvMonth;
		this.sbAdvItems = sbAdvItems;
		this.sbAdvChrg = sbAdvChrg;
		this.sbOtherAdvReason = sbOtherAdvReason;
		this.sbRecOfAdvReason = sbRecOfAdvReason;
		this.sbTotAuthByPpa = sbTotAuthByPpa;
		this.sbTotAuthByHa = sbTotAuthByHa;
		this.sbDispDateMonth = sbDispDateMonth;
		this.sbDispDateYear = sbDispDateYear;
		this.sbTotBasPrice = sbTotBasPrice;
		this.sbDiscount = sbDiscount;
		this.sbTotBasPriceZd = sbTotBasPriceZd;
		this.sbOopExp = sbOopExp;
		this.sbContAll = sbContAll;
		this.sbContCon = sbContCon;
		this.sbOxyCylMsk = sbOxyCylMsk;
		this.sbOxyExp = sbOxyExp;
		this.sbOxyAdj = sbOxyAdj;
		this.sbAdjVal = sbAdjVal;
		this.sbStProfFees = sbStProfFees;
		this.sbSpProfFees = sbSpProfFees;
		this.sbMpPfees = sbMpPfees;
		this.sbPfees2a = sbPfees2a;
		this.sbPfees2b = sbPfees2b;
		this.sbPfees2c = sbPfees2c;
		this.sbPfees2d = sbPfees2d;
		this.sbPfees2e = sbPfees2e;
		this.sbPfees2f = sbPfees2f;
		this.sbPfees2g = sbPfees2g;
		this.sbExpPrescFees = sbExpPrescFees;
		this.sbAddProfPay = sbAddProfPay;
		this.sbPrescChNew = sbPrescChNew;
		this.sbPrescChOld = sbPrescChOld;
		this.sbOtherAdj = sbOtherAdj;
		this.sbSubBpTotCalc = sbSubBpTotCalc;
		this.sbReimbTotCalc = sbReimbTotCalc;
		this.sbAddProfFees = sbAddProfFees;
		this.sbRemunTot = sbRemunTot;
		this.sbTotDed = sbTotDed;
		this.sbTotOfAcc = sbTotOfAcc;
		this.sbNetAmt = sbNetAmt;
		this.sbRecOfAdvCalc = sbRecOfAdvCalc;
		this.sbOthAdjAdv = sbOthAdjAdv;
		this.sbTotLaPay = sbTotLaPay;
		this.sbTotLaOther = sbTotLaOther;
		this.murNum = murNum;
		this.fp57NumForms = fp57NumForms;
		this.dispItemsNum = dispItemsNum;
		this.practicePayment = practicePayment;
		this.estabFee = estabFee;
		this.murFee = murFee;
		this.nmsFee = nmsFee;
		this.repeatSetup = repeatSetup;
		this.subTotalOfPrescFee = subTotalOfPrescFee;
		this.balDueRespOf = balDueRespOf;
		this.sbElhoseValue = sbElhoseValue;
		this.sbAvgItemValue = sbAvgItemValue;
		this.localPayLineId = localPayLineId;
		this.localPayLineDesc = localPayLineDesc;
		this.localPayLineValue = localPayLineValue;
		this.wgAeLineType = wgAeLineType;
		this.wgAeIdentifier = wgAeIdentifier;
		this.wgAeReasonCode = wgAeReasonCode;
		this.wgAeDescription = wgAeDescription;
		this.wgAeNumPxs = wgAeNumPxs;
		this.expItemsLimit2 = expItemsLimit2;
		this.expValueLimit2 = expValueLimit2;
		this.expItemsLimit1 = expItemsLimit1;
		this.expValueLimit1 = expValueLimit1;
		this.expTotItems = expTotItems;
		this.expTotValue = expTotValue;
		this.expensiveItemLine = expensiveItemLine;
		this.expItemDescription = expItemDescription;
		this.expItemPack = expItemPack;
		this.expItemQty = expItemQty;
		this.expItemValue = expItemValue;
		this.expensiveItemForm = expensiveItemForm;
		this.trlrBranchCount = trlrBranchCount;
		this.trlrTotalValue = trlrTotalValue;
		this.sbPfees2bHome = sbPfees2bHome;
		this.aurHomeFee = aurHomeFee;
		this.aurPremFee = aurPremFee;
		this.stomaCustValue = stomaCustValue;
		this.recAddAdvPay = recAddAdvPay;
		this.addAdvPay = addAdvPay;
		this.sbEtpForms = sbEtpForms;
		this.sbEtpItems = sbEtpItems;
		this.nmsNum = nmsNum;
		this.nmsItem = nmsItem;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
		this.mPayment=mPayment;
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Date getPaymentDate() {
		return paymentDate;
	}

	public void setPaymentDate(Date paymentDate) {
		this.paymentDate = paymentDate;
	}

	public double getContRate() {
		return contRate;
	}

	public void setContRate(double contRate) {
		this.contRate = contRate;
	}

	public double getStProfFee() {
		return stProfFee;
	}

	public void setStProfFee(double stProfFee) {
		this.stProfFee = stProfFee;
	}

	public double getSpProfFee() {
		return spProfFee;
	}

	public void setSpProfFee(double spProfFee) {
		this.spProfFee = spProfFee;
	}

	public short getExpItemsLowerLimit() {
		return expItemsLowerLimit;
	}

	public void setExpItemsLowerLimit(short expItemsLowerLimit) {
		this.expItemsLowerLimit = expItemsLowerLimit;
	}

	public short getExpItemsUpperLimit() {
		return expItemsUpperLimit;
	}

	public void setExpItemsUpperLimit(short expItemsUpperLimit) {
		this.expItemsUpperLimit = expItemsUpperLimit;
	}

	public String getMbOcsCode() {
		return mbOcsCode;
	}

	public void setMbOcsCode(String mbOcsCode) {
		this.mbOcsCode = mbOcsCode;
	}

	public String getMbCorName() {
		return mbCorName;
	}

	public void setMbCorName(String mbCorName) {
		this.mbCorName = mbCorName;
	}

	public short getMbShopNo() {
		return mbShopNo;
	}

	public void setMbShopNo(short mbShopNo) {
		this.mbShopNo = mbShopNo;
	}

	public String getMbTradename() {
		return mbTradename;
	}

	public void setMbTradename(String mbTradename) {
		this.mbTradename = mbTradename;
	}

	public String getMbCorAddress1() {
		return mbCorAddress1;
	}

	public void setMbCorAddress1(String mbCorAddress1) {
		this.mbCorAddress1 = mbCorAddress1;
	}

	public String getMbCorAddress2() {
		return mbCorAddress2;
	}

	public void setMbCorAddress2(String mbCorAddress2) {
		this.mbCorAddress2 = mbCorAddress2;
	}

	public String getMbCorAddress3() {
		return mbCorAddress3;
	}

	public void setMbCorAddress3(String mbCorAddress3) {
		this.mbCorAddress3 = mbCorAddress3;
	}

	public String getMbCorAddress4() {
		return mbCorAddress4;
	}

	public void setMbCorAddress4(String mbCorAddress4) {
		this.mbCorAddress4 = mbCorAddress4;
	}

	public String getMbCorPostcode() {
		return mbCorPostcode;
	}

	public void setMbCorPostcode(String mbCorPostcode) {
		this.mbCorPostcode = mbCorPostcode;
	}

	public String getMbName() {
		return mbName;
	}

	public void setMbName(String mbName) {
		this.mbName = mbName;
	}

	public String getMbPremAdd1() {
		return mbPremAdd1;
	}

	public void setMbPremAdd1(String mbPremAdd1) {
		this.mbPremAdd1 = mbPremAdd1;
	}

	public String getMbPremAdd2() {
		return mbPremAdd2;
	}

	public void setMbPremAdd2(String mbPremAdd2) {
		this.mbPremAdd2 = mbPremAdd2;
	}

	public String getMbPremAdd3() {
		return mbPremAdd3;
	}

	public void setMbPremAdd3(String mbPremAdd3) {
		this.mbPremAdd3 = mbPremAdd3;
	}

	public String getMbPremAdd4() {
		return mbPremAdd4;
	}

	public void setMbPremAdd4(String mbPremAdd4) {
		this.mbPremAdd4 = mbPremAdd4;
	}

	public String getMbPremPcode() {
		return mbPremPcode;
	}

	public void setMbPremPcode(String mbPremPcode) {
		this.mbPremPcode = mbPremPcode;
	}

	public String getMbFhsaCode() {
		return mbFhsaCode;
	}

	public void setMbFhsaCode(String mbFhsaCode) {
		this.mbFhsaCode = mbFhsaCode;
	}

	public String getMbPpaAccCode() {
		return mbPpaAccCode;
	}

	public void setMbPpaAccCode(String mbPpaAccCode) {
		this.mbPpaAccCode = mbPpaAccCode;
	}

	public String getMbNameOfAccount() {
		return mbNameOfAccount;
	}

	public void setMbNameOfAccount(String mbNameOfAccount) {
		this.mbNameOfAccount = mbNameOfAccount;
	}

	public String getMbBankAccountNumber() {
		return mbBankAccountNumber;
	}

	public void setMbBankAccountNumber(String mbBankAccountNumber) {
		this.mbBankAccountNumber = mbBankAccountNumber;
	}

	public String getMbBuildingSocRef() {
		return mbBuildingSocRef;
	}

	public void setMbBuildingSocRef(String mbBuildingSocRef) {
		this.mbBuildingSocRef = mbBuildingSocRef;
	}

	public String getMbSortCode() {
		return mbSortCode;
	}

	public void setMbSortCode(String mbSortCode) {
		this.mbSortCode = mbSortCode;
	}

	public String getMbTypeOfAccount() {
		return mbTypeOfAccount;
	}

	public void setMbTypeOfAccount(String mbTypeOfAccount) {
		this.mbTypeOfAccount = mbTypeOfAccount;
	}

	public String getMbPaymentMethod() {
		return mbPaymentMethod;
	}

	public void setMbPaymentMethod(String mbPaymentMethod) {
		this.mbPaymentMethod = mbPaymentMethod;
	}

	public double getMbPayment() {
		return mbPayment;
	}

	public void setMbPayment(double mbPayment) {
		this.mbPayment = mbPayment;
	}

	public String getMbRemitDispDate() {
		return mbRemitDispDate;
	}

	public void setMbRemitDispDate(String mbRemitDispDate) {
		this.mbRemitDispDate = mbRemitDispDate;
	}

	public String getSb300() {
		return sb300;
	}

	public void setSb300(String sb300) {
		this.sb300 = sb300;
	}

	public String getSbMbOcsCode() {
		return sbMbOcsCode;
	}

	public void setSbMbOcsCode(String sbMbOcsCode) {
		this.sbMbOcsCode = sbMbOcsCode;
	}

	public String getSbHaQcode() {
		return sbHaQcode;
	}

	public void setSbHaQcode(String sbHaQcode) {
		this.sbHaQcode = sbHaQcode;
	}

	public String getSbOcsCode() {
		return sbOcsCode;
	}

	public void setSbOcsCode(String sbOcsCode) {
		this.sbOcsCode = sbOcsCode;
	}

	public String getSbTaName() {
		return sbTaName;
	}

	public void setSbTaName(String sbTaName) {
		this.sbTaName = sbTaName;
	}

	public String getSbName() {
		return sbName;
	}

	public void setSbName(String sbName) {
		this.sbName = sbName;
	}

	public String getSbAddress1() {
		return sbAddress1;
	}

	public void setSbAddress1(String sbAddress1) {
		this.sbAddress1 = sbAddress1;
	}

	public String getSbAddress2() {
		return sbAddress2;
	}

	public void setSbAddress2(String sbAddress2) {
		this.sbAddress2 = sbAddress2;
	}

	public String getSbAddress3() {
		return sbAddress3;
	}

	public void setSbAddress3(String sbAddress3) {
		this.sbAddress3 = sbAddress3;
	}

	public String getSbAddressPostCode() {
		return sbAddressPostCode;
	}

	public void setSbAddressPostCode(String sbAddressPostCode) {
		this.sbAddressPostCode = sbAddressPostCode;
	}

	public String getSbHealthAuthority() {
		return sbHealthAuthority;
	}

	public void setSbHealthAuthority(String sbHealthAuthority) {
		this.sbHealthAuthority = sbHealthAuthority;
	}

	public String getSbConPpaCode() {
		return sbConPpaCode;
	}

	public void setSbConPpaCode(String sbConPpaCode) {
		this.sbConPpaCode = sbConPpaCode;
	}

	public String getSbConLaLine() {
		return sbConLaLine;
	}

	public void setSbConLaLine(String sbConLaLine) {
		this.sbConLaLine = sbConLaLine;
	}

	public double getSbPayment() {
		return sbPayment;
	}

	public void setSbPayment(double sbPayment) {
		this.sbPayment = sbPayment;
	}

	public short getSbConFormsRec() {
		return sbConFormsRec;
	}

	public void setSbConFormsRec(short sbConFormsRec) {
		this.sbConFormsRec = sbConFormsRec;
	}

	public short getSbConItemsSdr() {
		return sbConItemsSdr;
	}

	public void setSbConItemsSdr(short sbConItemsSdr) {
		this.sbConItemsSdr = sbConItemsSdr;
	}

	public short getSbConItemsZd() {
		return sbConItemsZd;
	}

	public void setSbConItemsZd(short sbConItemsZd) {
		this.sbConItemsZd = sbConItemsZd;
	}

	public short getSbConFormsRb() {
		return sbConFormsRb;
	}

	public void setSbConFormsRb(short sbConFormsRb) {
		this.sbConFormsRb = sbConFormsRb;
	}

	public short getSbConItemsRb() {
		return sbConItemsRb;
	}

	public void setSbConItemsRb(short sbConItemsRb) {
		this.sbConItemsRb = sbConItemsRb;
	}

	public double getSbConDisc() {
		return sbConDisc;
	}

	public void setSbConDisc(double sbConDisc) {
		this.sbConDisc = sbConDisc;
	}

	public short getSbConNumConAll() {
		return sbConNumConAll;
	}

	public void setSbConNumConAll(short sbConNumConAll) {
		this.sbConNumConAll = sbConNumConAll;
	}

	public String getSbConAdjText() {
		return sbConAdjText;
	}

	public void setSbConAdjText(String sbConAdjText) {
		this.sbConAdjText = sbConAdjText;
	}

	public short getSbNoStproFees() {
		return sbNoStproFees;
	}

	public void setSbNoStproFees(short sbNoStproFees) {
		this.sbNoStproFees = sbNoStproFees;
	}

	public short getSbNoSprofFees() {
		return sbNoSprofFees;
	}

	public void setSbNoSprofFees(short sbNoSprofFees) {
		this.sbNoSprofFees = sbNoSprofFees;
	}

	public double getSbNoEprescFees() {
		return sbNoEprescFees;
	}

	public void setSbNoEprescFees(double sbNoEprescFees) {
		this.sbNoEprescFees = sbNoEprescFees;
	}

	public double getSbRecovery() {
		return sbRecovery;
	}

	public void setSbRecovery(double sbRecovery) {
		this.sbRecovery = sbRecovery;
	}

	public short getSbNoPrescNew() {
		return sbNoPrescNew;
	}

	public void setSbNoPrescNew(short sbNoPrescNew) {
		this.sbNoPrescNew = sbNoPrescNew;
	}

	public double getSbPrescRateNew() {
		return sbPrescRateNew;
	}

	public void setSbPrescRateNew(double sbPrescRateNew) {
		this.sbPrescRateNew = sbPrescRateNew;
	}

	public double getSbNoPrescOld() {
		return sbNoPrescOld;
	}

	public void setSbNoPrescOld(double sbNoPrescOld) {
		this.sbNoPrescOld = sbNoPrescOld;
	}

	public double getSbPrescRateOld() {
		return sbPrescRateOld;
	}

	public void setSbPrescRateOld(double sbPrescRateOld) {
		this.sbPrescRateOld = sbPrescRateOld;
	}

	public double getSbAdvPayment() {
		return sbAdvPayment;
	}

	public void setSbAdvPayment(double sbAdvPayment) {
		this.sbAdvPayment = sbAdvPayment;
	}

	public String getSbAdvMonth() {
		return sbAdvMonth;
	}

	public void setSbAdvMonth(String sbAdvMonth) {
		this.sbAdvMonth = sbAdvMonth;
	}

	public short getSbAdvItems() {
		return sbAdvItems;
	}

	public void setSbAdvItems(short sbAdvItems) {
		this.sbAdvItems = sbAdvItems;
	}

	public short getSbAdvChrg() {
		return sbAdvChrg;
	}

	public void setSbAdvChrg(short sbAdvChrg) {
		this.sbAdvChrg = sbAdvChrg;
	}

	public String getSbOtherAdvReason() {
		return sbOtherAdvReason;
	}

	public void setSbOtherAdvReason(String sbOtherAdvReason) {
		this.sbOtherAdvReason = sbOtherAdvReason;
	}

	public String getSbRecOfAdvReason() {
		return sbRecOfAdvReason;
	}

	public void setSbRecOfAdvReason(String sbRecOfAdvReason) {
		this.sbRecOfAdvReason = sbRecOfAdvReason;
	}

	public double getSbTotAuthByPpa() {
		return sbTotAuthByPpa;
	}

	public void setSbTotAuthByPpa(double sbTotAuthByPpa) {
		this.sbTotAuthByPpa = sbTotAuthByPpa;
	}

	public double getSbTotAuthByHa() {
		return sbTotAuthByHa;
	}

	public void setSbTotAuthByHa(double sbTotAuthByHa) {
		this.sbTotAuthByHa = sbTotAuthByHa;
	}

	public String getSbDispDateMonth() {
		return sbDispDateMonth;
	}

	public void setSbDispDateMonth(String sbDispDateMonth) {
		this.sbDispDateMonth = sbDispDateMonth;
	}

	public short getSbDispDateYear() {
		return sbDispDateYear;
	}

	public void setSbDispDateYear(short sbDispDateYear) {
		this.sbDispDateYear = sbDispDateYear;
	}

	public double getSbTotBasPrice() {
		return sbTotBasPrice;
	}

	public void setSbTotBasPrice(double sbTotBasPrice) {
		this.sbTotBasPrice = sbTotBasPrice;
	}

	public double getSbDiscount() {
		return sbDiscount;
	}

	public void setSbDiscount(double sbDiscount) {
		this.sbDiscount = sbDiscount;
	}

	public double getSbTotBasPriceZd() {
		return sbTotBasPriceZd;
	}

	public void setSbTotBasPriceZd(double sbTotBasPriceZd) {
		this.sbTotBasPriceZd = sbTotBasPriceZd;
	}

	public double getSbOopExp() {
		return sbOopExp;
	}

	public void setSbOopExp(double sbOopExp) {
		this.sbOopExp = sbOopExp;
	}

	public double getSbContAll() {
		return sbContAll;
	}

	public void setSbContAll(double sbContAll) {
		this.sbContAll = sbContAll;
	}

	public double getSbContCon() {
		return sbContCon;
	}

	public void setSbContCon(double sbContCon) {
		this.sbContCon = sbContCon;
	}

	public double getSbOxyCylMsk() {
		return sbOxyCylMsk;
	}

	public void setSbOxyCylMsk(double sbOxyCylMsk) {
		this.sbOxyCylMsk = sbOxyCylMsk;
	}

	public double getSbOxyExp() {
		return sbOxyExp;
	}

	public void setSbOxyExp(double sbOxyExp) {
		this.sbOxyExp = sbOxyExp;
	}

	public double getSbOxyAdj() {
		return sbOxyAdj;
	}

	public void setSbOxyAdj(double sbOxyAdj) {
		this.sbOxyAdj = sbOxyAdj;
	}

	public double getSbAdjVal() {
		return sbAdjVal;
	}

	public void setSbAdjVal(double sbAdjVal) {
		this.sbAdjVal = sbAdjVal;
	}

	public double getSbStProfFees() {
		return sbStProfFees;
	}

	public void setSbStProfFees(double sbStProfFees) {
		this.sbStProfFees = sbStProfFees;
	}

	public double getSbSpProfFees() {
		return sbSpProfFees;
	}

	public void setSbSpProfFees(double sbSpProfFees) {
		this.sbSpProfFees = sbSpProfFees;
	}

	public double getSbMpPfees() {
		return sbMpPfees;
	}

	public void setSbMpPfees(double sbMpPfees) {
		this.sbMpPfees = sbMpPfees;
	}

	public double getSbPfees2a() {
		return sbPfees2a;
	}

	public void setSbPfees2a(double sbPfees2a) {
		this.sbPfees2a = sbPfees2a;
	}

	public double getSbPfees2b() {
		return sbPfees2b;
	}

	public void setSbPfees2b(double sbPfees2b) {
		this.sbPfees2b = sbPfees2b;
	}

	public double getSbPfees2c() {
		return sbPfees2c;
	}

	public void setSbPfees2c(double sbPfees2c) {
		this.sbPfees2c = sbPfees2c;
	}

	public double getSbPfees2d() {
		return sbPfees2d;
	}

	public void setSbPfees2d(double sbPfees2d) {
		this.sbPfees2d = sbPfees2d;
	}

	public double getSbPfees2e() {
		return sbPfees2e;
	}

	public void setSbPfees2e(double sbPfees2e) {
		this.sbPfees2e = sbPfees2e;
	}

	public double getSbPfees2f() {
		return sbPfees2f;
	}

	public void setSbPfees2f(double sbPfees2f) {
		this.sbPfees2f = sbPfees2f;
	}

	public double getSbPfees2g() {
		return sbPfees2g;
	}

	public void setSbPfees2g(double sbPfees2g) {
		this.sbPfees2g = sbPfees2g;
	}

	public double getSbExpPrescFees() {
		return sbExpPrescFees;
	}

	public void setSbExpPrescFees(double sbExpPrescFees) {
		this.sbExpPrescFees = sbExpPrescFees;
	}

	public double getSbAddProfPay() {
		return sbAddProfPay;
	}

	public void setSbAddProfPay(double sbAddProfPay) {
		this.sbAddProfPay = sbAddProfPay;
	}

	public double getSbPrescChNew() {
		return sbPrescChNew;
	}

	public void setSbPrescChNew(double sbPrescChNew) {
		this.sbPrescChNew = sbPrescChNew;
	}

	public double getSbPrescChOld() {
		return sbPrescChOld;
	}

	public void setSbPrescChOld(double sbPrescChOld) {
		this.sbPrescChOld = sbPrescChOld;
	}

	public double getSbOtherAdj() {
		return sbOtherAdj;
	}

	public void setSbOtherAdj(double sbOtherAdj) {
		this.sbOtherAdj = sbOtherAdj;
	}

	public double getSbSubBpTotCalc() {
		return sbSubBpTotCalc;
	}

	public void setSbSubBpTotCalc(double sbSubBpTotCalc) {
		this.sbSubBpTotCalc = sbSubBpTotCalc;
	}

	public double getSbReimbTotCalc() {
		return sbReimbTotCalc;
	}

	public void setSbReimbTotCalc(double sbReimbTotCalc) {
		this.sbReimbTotCalc = sbReimbTotCalc;
	}

	public double getSbAddProfFees() {
		return sbAddProfFees;
	}

	public void setSbAddProfFees(double sbAddProfFees) {
		this.sbAddProfFees = sbAddProfFees;
	}

	public double getSbRemunTot() {
		return sbRemunTot;
	}

	public void setSbRemunTot(double sbRemunTot) {
		this.sbRemunTot = sbRemunTot;
	}

	public double getSbTotDed() {
		return sbTotDed;
	}

	public void setSbTotDed(double sbTotDed) {
		this.sbTotDed = sbTotDed;
	}

	public double getSbTotOfAcc() {
		return sbTotOfAcc;
	}

	public void setSbTotOfAcc(double sbTotOfAcc) {
		this.sbTotOfAcc = sbTotOfAcc;
	}

	public double getSbNetAmt() {
		return sbNetAmt;
	}

	public void setSbNetAmt(double sbNetAmt) {
		this.sbNetAmt = sbNetAmt;
	}

	public double getSbRecOfAdvCalc() {
		return sbRecOfAdvCalc;
	}

	public void setSbRecOfAdvCalc(double sbRecOfAdvCalc) {
		this.sbRecOfAdvCalc = sbRecOfAdvCalc;
	}

	public double getSbOthAdjAdv() {
		return sbOthAdjAdv;
	}

	public void setSbOthAdjAdv(double sbOthAdjAdv) {
		this.sbOthAdjAdv = sbOthAdjAdv;
	}

	public double getSbTotLaPay() {
		return sbTotLaPay;
	}

	public void setSbTotLaPay(double sbTotLaPay) {
		this.sbTotLaPay = sbTotLaPay;
	}

	public double getSbTotLaOther() {
		return sbTotLaOther;
	}

	public void setSbTotLaOther(double sbTotLaOther) {
		this.sbTotLaOther = sbTotLaOther;
	}

	public double getMurNum() {
		return murNum;
	}

	public void setMurNum(double murNum) {
		this.murNum = murNum;
	}

	public double getFp57NumForms() {
		return fp57NumForms;
	}

	public void setFp57NumForms(double fp57NumForms) {
		this.fp57NumForms = fp57NumForms;
	}

	public double getDispItemsNum() {
		return dispItemsNum;
	}

	public void setDispItemsNum(double dispItemsNum) {
		this.dispItemsNum = dispItemsNum;
	}

	public double getPracticePayment() {
		return practicePayment;
	}

	public void setPracticePayment(double practicePayment) {
		this.practicePayment = practicePayment;
	}

	public double getEstabFee() {
		return estabFee;
	}

	public void setEstabFee(double estabFee) {
		this.estabFee = estabFee;
	}

	public double getMurFee() {
		return murFee;
	}

	public void setMurFee(double murFee) {
		this.murFee = murFee;
	}

	public double getNmsFee() {
		return nmsFee;
	}

	public void setNmsFee(double nmsFee) {
		this.nmsFee = nmsFee;
	}

	public double getRepeatSetup() {
		return repeatSetup;
	}

	public void setRepeatSetup(double repeatSetup) {
		this.repeatSetup = repeatSetup;
	}

	public double getSubTotalOfPrescFee() {
		return subTotalOfPrescFee;
	}

	public void setSubTotalOfPrescFee(double subTotalOfPrescFee) {
		this.subTotalOfPrescFee = subTotalOfPrescFee;
	}

	public double getBalDueRespOf() {
		return balDueRespOf;
	}

	public void setBalDueRespOf(double balDueRespOf) {
		this.balDueRespOf = balDueRespOf;
	}

	public double getSbElhoseValue() {
		return sbElhoseValue;
	}

	public void setSbElhoseValue(double sbElhoseValue) {
		this.sbElhoseValue = sbElhoseValue;
	}

	public double getSbAvgItemValue() {
		return sbAvgItemValue;
	}

	public void setSbAvgItemValue(double sbAvgItemValue) {
		this.sbAvgItemValue = sbAvgItemValue;
	}

	public short getLocalPayLineId() {
		return localPayLineId;
	}

	public void setLocalPayLineId(short localPayLineId) {
		this.localPayLineId = localPayLineId;
	}

	public String getLocalPayLineDesc() {
		return localPayLineDesc;
	}

	public void setLocalPayLineDesc(String localPayLineDesc) {
		this.localPayLineDesc = localPayLineDesc;
	}

	public double getLocalPayLineValue() {
		return localPayLineValue;
	}

	public void setLocalPayLineValue(double localPayLineValue) {
		this.localPayLineValue = localPayLineValue;
	}

	public short getWgAeLineType() {
		return wgAeLineType;
	}

	public void setWgAeLineType(short wgAeLineType) {
		this.wgAeLineType = wgAeLineType;
	}

	public String getWgAeIdentifier() {
		return wgAeIdentifier;
	}

	public void setWgAeIdentifier(String wgAeIdentifier) {
		this.wgAeIdentifier = wgAeIdentifier;
	}

	public String getWgAeReasonCode() {
		return wgAeReasonCode;
	}

	public void setWgAeReasonCode(String wgAeReasonCode) {
		this.wgAeReasonCode = wgAeReasonCode;
	}

	public String getWgAeDescription() {
		return wgAeDescription;
	}

	public void setWgAeDescription(String wgAeDescription) {
		this.wgAeDescription = wgAeDescription;
	}

	public short getWgAeNumPxs() {
		return wgAeNumPxs;
	}

	public void setWgAeNumPxs(short wgAeNumPxs) {
		this.wgAeNumPxs = wgAeNumPxs;
	}

	public short getExpItemsLimit2() {
		return expItemsLimit2;
	}

	public void setExpItemsLimit2(short expItemsLimit2) {
		this.expItemsLimit2 = expItemsLimit2;
	}

	public double getExpValueLimit2() {
		return expValueLimit2;
	}

	public void setExpValueLimit2(double expValueLimit2) {
		this.expValueLimit2 = expValueLimit2;
	}

	public short getExpItemsLimit1() {
		return expItemsLimit1;
	}

	public void setExpItemsLimit1(short expItemsLimit1) {
		this.expItemsLimit1 = expItemsLimit1;
	}

	public double getExpValueLimit1() {
		return expValueLimit1;
	}

	public void setExpValueLimit1(double expValueLimit1) {
		this.expValueLimit1 = expValueLimit1;
	}

	public short getExpTotItems() {
		return expTotItems;
	}

	public void setExpTotItems(short expTotItems) {
		this.expTotItems = expTotItems;
	}

	public double getExpTotValue() {
		return expTotValue;
	}

	public void setExpTotValue(double expTotValue) {
		this.expTotValue = expTotValue;
	}

	public String getExpensiveItemLine() {
		return expensiveItemLine;
	}

	public void setExpensiveItemLine(String expensiveItemLine) {
		this.expensiveItemLine = expensiveItemLine;
	}

	public String getExpItemDescription() {
		return expItemDescription;
	}

	public void setExpItemDescription(String expItemDescription) {
		this.expItemDescription = expItemDescription;
	}

	public double getExpItemPack() {
		return expItemPack;
	}

	public void setExpItemPack(double expItemPack) {
		this.expItemPack = expItemPack;
	}

	public short getExpItemQty() {
		return expItemQty;
	}

	public void setExpItemQty(short expItemQty) {
		this.expItemQty = expItemQty;
	}

	public double getExpItemValue() {
		return expItemValue;
	}

	public void setExpItemValue(double expItemValue) {
		this.expItemValue = expItemValue;
	}

	public short getExpensiveItemForm() {
		return expensiveItemForm;
	}

	public void setExpensiveItemForm(short expensiveItemForm) {
		this.expensiveItemForm = expensiveItemForm;
	}

	public short getTrlrBranchCount() {
		return trlrBranchCount;
	}

	public void setTrlrBranchCount(short trlrBranchCount) {
		this.trlrBranchCount = trlrBranchCount;
	}

	public double getTrlrTotalValue() {
		return trlrTotalValue;
	}

	public void setTrlrTotalValue(double trlrTotalValue) {
		this.trlrTotalValue = trlrTotalValue;
	}

	public double getSbPfees2bHome() {
		return sbPfees2bHome;
	}

	public void setSbPfees2bHome(double sbPfees2bHome) {
		this.sbPfees2bHome = sbPfees2bHome;
	}

	public double getAurHomeFee() {
		return aurHomeFee;
	}

	public void setAurHomeFee(double aurHomeFee) {
		this.aurHomeFee = aurHomeFee;
	}

	public double getAurPremFee() {
		return aurPremFee;
	}

	public void setAurPremFee(double aurPremFee) {
		this.aurPremFee = aurPremFee;
	}

	public double getStomaCustValue() {
		return stomaCustValue;
	}

	public void setStomaCustValue(double stomaCustValue) {
		this.stomaCustValue = stomaCustValue;
	}

	public double getRecAddAdvPay() {
		return recAddAdvPay;
	}

	public void setRecAddAdvPay(double recAddAdvPay) {
		this.recAddAdvPay = recAddAdvPay;
	}

	public double getAddAdvPay() {
		return addAdvPay;
	}

	public void setAddAdvPay(double addAdvPay) {
		this.addAdvPay = addAdvPay;
	}

	public short getSbEtpForms() {
		return sbEtpForms;
	}

	public void setSbEtpForms(short sbEtpForms) {
		this.sbEtpForms = sbEtpForms;
	}

	public double getSbEtpItems() {
		return sbEtpItems;
	}

	public void setSbEtpItems(double sbEtpItems) {
		this.sbEtpItems = sbEtpItems;
	}

	public double getNmsNum() {
		return nmsNum;
	}

	public void setNmsNum(double nmsNum) {
		this.nmsNum = nmsNum;
	}

	public short getNmsItem() {
		return nmsItem;
	}

	public void setNmsItem(short nmsItem) {
		this.nmsItem = nmsItem;
	}

	public String getCreatedBy() {
		return createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreatedDate() {
		return createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getUpdatedBy() {
		return updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	public Date getUpdatedDate() {
		return updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	public String getMbHaQcode() {
		return mbHaQcode;
	}

	public void setMbHaQcode(String mbHaQcode) {
		this.mbHaQcode = mbHaQcode;
	}

	
	
	public double getmPayment() {
		return mPayment;
	}

	public void setmPayment(double mPayment) {
		this.mPayment = mPayment;
	}

	@Override
	public String toString() {
		return "PpaData [id=" + id + ", paymentDate=" + paymentDate + ", contRate=" + contRate + ", stProfFee="
				+ stProfFee + ", spProfFee=" + spProfFee + ", expItemsLowerLimit=" + expItemsLowerLimit
				+ ", expItemsUpperLimit=" + expItemsUpperLimit + ", mbHaQcode=" + mbHaQcode + ", mbOcsCode=" + mbOcsCode
				+ ", mbCorName=" + mbCorName + ", mbShopNo=" + mbShopNo + ", mbTradename=" + mbTradename
				+ ", mbCorAddress1=" + mbCorAddress1 + ", mbCorAddress2=" + mbCorAddress2 + ", mbCorAddress3="
				+ mbCorAddress3 + ", mbCorAddress4=" + mbCorAddress4 + ", mbCorPostcode=" + mbCorPostcode + ", mbName="
				+ mbName + ", mbPremAdd1=" + mbPremAdd1 + ", mbPremAdd2=" + mbPremAdd2 + ", mbPremAdd3=" + mbPremAdd3
				+ ", mbPremAdd4=" + mbPremAdd4 + ", mbPremPcode=" + mbPremPcode + ", mbFhsaCode=" + mbFhsaCode
				+ ", mbPpaAccCode=" + mbPpaAccCode + ", mbNameOfAccount=" + mbNameOfAccount + ", mbBankAccountNumber="
				+ mbBankAccountNumber + ", mbBuildingSocRef=" + mbBuildingSocRef + ", mbSortCode=" + mbSortCode
				+ ", mbTypeOfAccount=" + mbTypeOfAccount + ", mbPaymentMethod=" + mbPaymentMethod + ", mbPayment="
				+ mbPayment + ", mbRemitDispDate=" + mbRemitDispDate + ", sb300=" + sb300 + ", sbMbOcsCode="
				+ sbMbOcsCode + ", sbHaQcode=" + sbHaQcode + ", sbOcsCode=" + sbOcsCode + ", sbTaName=" + sbTaName
				+ ", sbName=" + sbName + ", sbAddress1=" + sbAddress1 + ", sbAddress2=" + sbAddress2 + ", sbAddress3="
				+ sbAddress3 + ", sbAddressPostCode=" + sbAddressPostCode + ", sbHealthAuthority=" + sbHealthAuthority
				+ ", sbConPpaCode=" + sbConPpaCode + ", sbConLaLine=" + sbConLaLine + ", sbPayment=" + sbPayment
				+ ", sbConFormsRec=" + sbConFormsRec + ", sbConItemsSdr=" + sbConItemsSdr + ", sbConItemsZd="
				+ sbConItemsZd + ", sbConFormsRb=" + sbConFormsRb + ", sbConItemsRb=" + sbConItemsRb + ", sbConDisc="
				+ sbConDisc + ", sbConNumConAll=" + sbConNumConAll + ", sbConAdjText=" + sbConAdjText
				+ ", sbNoStproFees=" + sbNoStproFees + ", sbNoSprofFees=" + sbNoSprofFees + ", sbNoEprescFees="
				+ sbNoEprescFees + ", sbRecovery=" + sbRecovery + ", sbNoPrescNew=" + sbNoPrescNew + ", sbPrescRateNew="
				+ sbPrescRateNew + ", sbNoPrescOld=" + sbNoPrescOld + ", sbPrescRateOld=" + sbPrescRateOld
				+ ", sbAdvPayment=" + sbAdvPayment + ", sbAdvMonth=" + sbAdvMonth + ", sbAdvItems=" + sbAdvItems
				+ ", sbAdvChrg=" + sbAdvChrg + ", sbOtherAdvReason=" + sbOtherAdvReason + ", sbRecOfAdvReason="
				+ sbRecOfAdvReason + ", sbTotAuthByPpa=" + sbTotAuthByPpa + ", sbTotAuthByHa=" + sbTotAuthByHa
				+ ", sbDispDateMonth=" + sbDispDateMonth + ", sbDispDateYear=" + sbDispDateYear + ", sbTotBasPrice="
				+ sbTotBasPrice + ", sbDiscount=" + sbDiscount + ", sbTotBasPriceZd=" + sbTotBasPriceZd + ", sbOopExp="
				+ sbOopExp + ", sbContAll=" + sbContAll + ", sbContCon=" + sbContCon + ", sbOxyCylMsk=" + sbOxyCylMsk
				+ ", sbOxyExp=" + sbOxyExp + ", sbOxyAdj=" + sbOxyAdj + ", sbAdjVal=" + sbAdjVal + ", sbStProfFees="
				+ sbStProfFees + ", sbSpProfFees=" + sbSpProfFees + ", sbMpPfees=" + sbMpPfees + ", sbPfees2a="
				+ sbPfees2a + ", sbPfees2b=" + sbPfees2b + ", sbPfees2c=" + sbPfees2c + ", sbPfees2d=" + sbPfees2d
				+ ", sbPfees2e=" + sbPfees2e + ", sbPfees2f=" + sbPfees2f + ", sbPfees2g=" + sbPfees2g
				+ ", sbExpPrescFees=" + sbExpPrescFees + ", sbAddProfPay=" + sbAddProfPay + ", sbPrescChNew="
				+ sbPrescChNew + ", sbPrescChOld=" + sbPrescChOld + ", sbOtherAdj=" + sbOtherAdj + ", sbSubBpTotCalc="
				+ sbSubBpTotCalc + ", sbReimbTotCalc=" + sbReimbTotCalc + ", sbAddProfFees=" + sbAddProfFees
				+ ", sbRemunTot=" + sbRemunTot + ", sbTotDed=" + sbTotDed + ", sbTotOfAcc=" + sbTotOfAcc + ", sbNetAmt="
				+ sbNetAmt + ", sbRecOfAdvCalc=" + sbRecOfAdvCalc + ", sbOthAdjAdv=" + sbOthAdjAdv + ", sbTotLaPay="
				+ sbTotLaPay + ", sbTotLaOther=" + sbTotLaOther + ", murNum=" + murNum + ", fp57NumForms="
				+ fp57NumForms + ", dispItemsNum=" + dispItemsNum + ", practicePayment=" + practicePayment
				+ ", estabFee=" + estabFee + ", murFee=" + murFee + ", nmsFee=" + nmsFee + ", repeatSetup="
				+ repeatSetup + ", subTotalOfPrescFee=" + subTotalOfPrescFee + ", balDueRespOf=" + balDueRespOf
				+ ", sbElhoseValue=" + sbElhoseValue + ", sbAvgItemValue=" + sbAvgItemValue + ", localPayLineId="
				+ localPayLineId + ", localPayLineDesc=" + localPayLineDesc + ", localPayLineValue=" + localPayLineValue
				+ ", wgAeLineType=" + wgAeLineType + ", wgAeIdentifier=" + wgAeIdentifier + ", wgAeReasonCode="
				+ wgAeReasonCode + ", wgAeDescription=" + wgAeDescription + ", wgAeNumPxs=" + wgAeNumPxs
				+ ", expItemsLimit2=" + expItemsLimit2 + ", expValueLimit2=" + expValueLimit2 + ", expItemsLimit1="
				+ expItemsLimit1 + ", expValueLimit1=" + expValueLimit1 + ", expTotItems=" + expTotItems
				+ ", expTotValue=" + expTotValue + ", expensiveItemLine=" + expensiveItemLine + ", expItemDescription="
				+ expItemDescription + ", expItemPack=" + expItemPack + ", expItemQty=" + expItemQty + ", expItemValue="
				+ expItemValue + ", expensiveItemForm=" + expensiveItemForm + ", trlrBranchCount=" + trlrBranchCount
				+ ", trlrTotalValue=" + trlrTotalValue + ", sbPfees2bHome=" + sbPfees2bHome + ", aurHomeFee="
				+ aurHomeFee + ", aurPremFee=" + aurPremFee + ", stomaCustValue=" + stomaCustValue + ", recAddAdvPay="
				+ recAddAdvPay + ", addAdvPay=" + addAdvPay + ", sbEtpForms=" + sbEtpForms + ", sbEtpItems="
				+ sbEtpItems + ", nmsNum=" + nmsNum + ", nmsItem=" + nmsItem + ", createdBy=" + createdBy
				+ ", createdDate=" + createdDate + ", updatedBy=" + updatedBy + ", updatedDate=" + updatedDate + "]";
	}

	
}
