// default package
// Generated 30-Mar-2018 12:11:34 by Hibernate Tools 5.1.0.Alpha1
package com.avee.form;

import java.util.Date;

/**
 * PpaMaster800 generated by hbm2java
 */

public class PpaMaster800 implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private int id;
	private Date paymentDate;
	private String sbOcsCode;
	private String mbTradename;
	private String sbConLaLine;
	private String expensiveItemLine;
	private String expItemDescription;
	private Double expItemPack;
	private Short expItemQty;
	private Double expItemValue;
	private String expensiveItemForm;

	public PpaMaster800() {
	}

	public PpaMaster800(int id, Date paymentDate) {
		this.id = id;
		this.paymentDate = paymentDate;
	}

	public PpaMaster800(int id, Date paymentDate, String sbOcsCode, String mbTradename, String sbConLaLine,
			String expensiveItemLine, String expItemDescription, Double expItemPack, Short expItemQty,
			Double expItemValue, String expensiveItemForm) {
		this.id = id;
		this.paymentDate = paymentDate;
		this.sbOcsCode = sbOcsCode;
		this.mbTradename = mbTradename;
		this.sbConLaLine = sbConLaLine;
		this.expensiveItemLine = expensiveItemLine;
		this.expItemDescription = expItemDescription;
		this.expItemPack = expItemPack;
		this.expItemQty = expItemQty;
		this.expItemValue = expItemValue;
		this.expensiveItemForm = expensiveItemForm;
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Date getPaymentDate() {
		return paymentDate;
	}

	public void setPaymentDate(Date paymentDate) {
		this.paymentDate = paymentDate;
	}

	public String getSbOcsCode() {
		return sbOcsCode;
	}

	public void setSbOcsCode(String sbOcsCode) {
		this.sbOcsCode = sbOcsCode;
	}

	public String getMbTradename() {
		return mbTradename;
	}

	public void setMbTradename(String mbTradename) {
		this.mbTradename = mbTradename;
	}

	public String getSbConLaLine() {
		return sbConLaLine;
	}

	public void setSbConLaLine(String sbConLaLine) {
		this.sbConLaLine = sbConLaLine;
	}

	public String getExpensiveItemLine() {
		return expensiveItemLine;
	}

	public void setExpensiveItemLine(String expensiveItemLine) {
		this.expensiveItemLine = expensiveItemLine;
	}

	public String getExpItemDescription() {
		return expItemDescription;
	}

	public void setExpItemDescription(String expItemDescription) {
		this.expItemDescription = expItemDescription;
	}

	public Double getExpItemPack() {
		return expItemPack;
	}

	public void setExpItemPack(Double expItemPack) {
		this.expItemPack = expItemPack;
	}

	public Short getExpItemQty() {
		return expItemQty;
	}

	public void setExpItemQty(Short expItemQty) {
		this.expItemQty = expItemQty;
	}

	public Double getExpItemValue() {
		return expItemValue;
	}

	public void setExpItemValue(Double expItemValue) {
		this.expItemValue = expItemValue;
	}

	public String getExpensiveItemForm() {
		return expensiveItemForm;
	}

	public void setExpensiveItemForm(String expensiveItemForm) {
		this.expensiveItemForm = expensiveItemForm;
	}

}
