package com.avee.form;

/**
 * UserRole generated by hbm2java
 */
@SuppressWarnings("serial")
public class UserTypeRole implements java.io.Serializable {

	private Role role;
	private UserType userType;
	
	public UserTypeRole() {
	}
	
	public UserTypeRole(Role role, UserType userType) {
		this.role = role;
		this.userType = userType;
	}

	public Role getRole() {
		return role;
	}
	public void setRole(Role role) {
		this.role = role;
	}

	public UserType getUserType() {
		return userType;
	}
	public void setUserType(UserType userType) {
		this.userType = userType;
	}
	
}
